@echo off
rem This file is generated by Bluetooth Developer Studio plugin.
rem     BDS Version    : 1.1.3139.0
rem     Script Version : 2.0.1

rem Please input the full path of BLE software top folder.
rem For example:
rem copy_sv_src.bat C:\workspace\Renesas\BLE_Software_Ver_1_20\RL78_G1D\Project_Source
rem 
rem If you want to backup original file, you enter a folder name to the second argument.
rem For example:
rem copy_sv_src.bat C:\workspace\Renesas\BLE_Software_Ver_1_20\RL78_G1D\Project_Source backup1


if "%1" equ "" (
    @echo Please input the full path of BLE software top folder.
    goto END
)

if "%2" neq "" (

    @echo make backup folder
    mkdir %2 > NUL 2>&1
    if ERRORLEVEL 1 (
        @echo Already exists a folder.
        goto END
    )

    @echo file backup
    copy %1\rBLE\src\sample_profile\sam\sam.h                .\%2
    copy %1\rBLE\src\sample_profile\sam\sams.c               .\%2
    copy %1\rBLE\src\sample_profile\sam\sams.h               .\%2
    copy %1\rBLE\src\sample_app\rble_sample_app_peripheral.c .\%2
    copy %1\rBLE\src\sample_app\rble_sample_app_peripheral.h .\%2
    copy %1\renesas\src\arch\rl78\db_handle.h                .\%2
    copy %1\renesas\src\arch\rl78\prf_config.c               .\%2
    copy %1\renesas\src\arch\rl78\prf_config.h               .\%2
    copy %1\renesas\src\arch\rl78\prf_sel.h                  .\%2

)

@echo copy the files.
copy sam.h                        %1\rBLE\src\sample_profile\sam
copy sams.c                       %1\rBLE\src\sample_profile\sam
copy sams.h                       %1\rBLE\src\sample_profile\sam
copy rble_sample_app_peripheral.c %1\rBLE\src\sample_app
copy rble_sample_app_peripheral.h %1\rBLE\src\sample_app
copy db_handle.h                  %1\renesas\src\arch\rl78
copy prf_config.c                 %1\renesas\src\arch\rl78
copy prf_config.h                 %1\renesas\src\arch\rl78
copy prf_sel.h                    %1\renesas\src\arch\rl78

:END
