/**
 ****************************************************************************************
 *
 * @file        prf_config.c
 *
 * @brief   Setting of Configuration Parameters for Profile
 *
 * Copyright (C) RivieraWaves 2009-2012
 *
 * Copyright(C) 2013-2017 Renesas Electronics Corporation
 *
 * This file is generated by Bluetooth Developer Studio plugin.
 *     BDS Version    : 1.1.3139.0
 *     Script Version : 2.0.1
 *
 ****************************************************************************************
 */

/**
 * INCLUDE FILES
 ****************************************************************************************
 */
#include "arch.h"
#include "rwke_api.h"

#include "prf_config.h"
#include "db_handle.h"
#include "rble_api.h"


#if USE_SAMPLE_PROFILE
/*******************************
 * Sample Custom Service       *
 *******************************/
/* Service ( Environmental Sensing ) */
static const uint8_t environmental_sensing_svc[RBLE_GATT_16BIT_UUID_OCTET] = RBLE_BDS_SVC_ENVIRONMENTAL_SENSING;

/* Characteristic ( Environmental Sensing: Descriptor Value Changed ) */
static const struct atts_char_desc es_descriptor_value_changed_char = {
	RBLE_GATT_CHAR_PROP_IND,
	{(uint8_t)(ENVIRONMENTAL_SENSING_HDL_ES_DESCRIPTOR_VALUE_CHANGED_VAL & 0xff),(uint8_t)((ENVIRONMENTAL_SENSING_HDL_ES_DESCRIPTOR_VALUE_CHANGED_VAL >> 8) & 0xff)},
	RBLE_BDS_CHAR_ES_DESCRIPTOR_VALUE_CHANGED};

uint8_t es_descriptor_value_changed_char_val = 0;

uint16_t es_descriptor_value_changed_char_cccd = 0;

/* Characteristic ( Environmental Sensing: Apparent Wind Direction ) */
static const struct atts_char_desc es_apparent_wind_direction_char = {
	RBLE_GATT_CHAR_PROP_NTF | RBLE_GATT_CHAR_PROP_RD,
	{(uint8_t)(ENVIRONMENTAL_SENSING_HDL_ES_APPARENT_WIND_DIRECTION_VAL & 0xff),(uint8_t)((ENVIRONMENTAL_SENSING_HDL_ES_APPARENT_WIND_DIRECTION_VAL >> 8) & 0xff)},
	RBLE_BDS_CHAR_ES_APPARENT_WIND_DIRECTION};

uint16_t es_apparent_wind_direction_char_val = 0;

uint16_t es_apparent_wind_direction_char_cccd = 0;

/* Characteristic ( Environmental Sensing: Apparent Wind Speed ) */
static const struct atts_char_desc es_apparent_wind_speed_char = {
	RBLE_GATT_CHAR_PROP_NTF | RBLE_GATT_CHAR_PROP_RD,
	{(uint8_t)(ENVIRONMENTAL_SENSING_HDL_ES_APPARENT_WIND_SPEED_VAL & 0xff),(uint8_t)((ENVIRONMENTAL_SENSING_HDL_ES_APPARENT_WIND_SPEED_VAL >> 8) & 0xff)},
	RBLE_BDS_CHAR_ES_APPARENT_WIND_SPEED};

uint16_t es_apparent_wind_speed_char_val = 0;

uint16_t es_apparent_wind_speed_char_cccd = 0;

/* Characteristic ( Environmental Sensing: Dew Point ) */
static const struct atts_char_desc es_dew_point_char = {
	RBLE_GATT_CHAR_PROP_NTF | RBLE_GATT_CHAR_PROP_RD,
	{(uint8_t)(ENVIRONMENTAL_SENSING_HDL_ES_DEW_POINT_VAL & 0xff),(uint8_t)((ENVIRONMENTAL_SENSING_HDL_ES_DEW_POINT_VAL >> 8) & 0xff)},
	RBLE_BDS_CHAR_ES_DEW_POINT};

int8_t es_dew_point_char_val = 0;

uint16_t es_dew_point_char_cccd = 0;

/* Characteristic ( Environmental Sensing: Elevation ) */
static const struct atts_char_desc es_elevation_char = {
	RBLE_GATT_CHAR_PROP_NTF | RBLE_GATT_CHAR_PROP_RD,
	{(uint8_t)(ENVIRONMENTAL_SENSING_HDL_ES_ELEVATION_VAL & 0xff),(uint8_t)((ENVIRONMENTAL_SENSING_HDL_ES_ELEVATION_VAL >> 8) & 0xff)},
	RBLE_BDS_CHAR_ES_ELEVATION};

int8_t es_elevation_char_val[3] = {0};

uint16_t es_elevation_char_cccd = 0;

/* Characteristic ( Environmental Sensing: Gust Factor ) */
static const struct atts_char_desc es_gust_factor_char = {
	RBLE_GATT_CHAR_PROP_NTF | RBLE_GATT_CHAR_PROP_RD,
	{(uint8_t)(ENVIRONMENTAL_SENSING_HDL_ES_GUST_FACTOR_VAL & 0xff),(uint8_t)((ENVIRONMENTAL_SENSING_HDL_ES_GUST_FACTOR_VAL >> 8) & 0xff)},
	RBLE_BDS_CHAR_ES_GUST_FACTOR};

uint8_t es_gust_factor_char_val = 0;

uint16_t es_gust_factor_char_cccd = 0;

/* Characteristic ( Environmental Sensing: Heat Index ) */
static const struct atts_char_desc es_heat_index_char = {
	RBLE_GATT_CHAR_PROP_NTF | RBLE_GATT_CHAR_PROP_RD,
	{(uint8_t)(ENVIRONMENTAL_SENSING_HDL_ES_HEAT_INDEX_VAL & 0xff),(uint8_t)((ENVIRONMENTAL_SENSING_HDL_ES_HEAT_INDEX_VAL >> 8) & 0xff)},
	RBLE_BDS_CHAR_ES_HEAT_INDEX};

int8_t es_heat_index_char_val = 0;

uint16_t es_heat_index_char_cccd = 0;

/* Characteristic ( Environmental Sensing: Humidity ) */
static const struct atts_char_desc es_humidity_char = {
	RBLE_GATT_CHAR_PROP_NTF | RBLE_GATT_CHAR_PROP_RD,
	{(uint8_t)(ENVIRONMENTAL_SENSING_HDL_ES_HUMIDITY_VAL & 0xff),(uint8_t)((ENVIRONMENTAL_SENSING_HDL_ES_HUMIDITY_VAL >> 8) & 0xff)},
	RBLE_BDS_CHAR_ES_HUMIDITY};

uint16_t es_humidity_char_val = 0;

uint16_t es_humidity_char_cccd = 0;

/* Characteristic ( Environmental Sensing: Irradiance ) */
static const struct atts_char_desc es_irradiance_char = {
	RBLE_GATT_CHAR_PROP_NTF | RBLE_GATT_CHAR_PROP_RD,
	{(uint8_t)(ENVIRONMENTAL_SENSING_HDL_ES_IRRADIANCE_VAL & 0xff),(uint8_t)((ENVIRONMENTAL_SENSING_HDL_ES_IRRADIANCE_VAL >> 8) & 0xff)},
	RBLE_BDS_CHAR_ES_IRRADIANCE};

uint16_t es_irradiance_char_val = 0;

uint16_t es_irradiance_char_cccd = 0;

/* Characteristic ( Environmental Sensing: Pollen Concentration ) */
static const struct atts_char_desc es_pollen_concentration_char = {
	RBLE_GATT_CHAR_PROP_NTF | RBLE_GATT_CHAR_PROP_RD,
	{(uint8_t)(ENVIRONMENTAL_SENSING_HDL_ES_POLLEN_CONCENTRATION_VAL & 0xff),(uint8_t)((ENVIRONMENTAL_SENSING_HDL_ES_POLLEN_CONCENTRATION_VAL >> 8) & 0xff)},
	RBLE_BDS_CHAR_ES_POLLEN_CONCENTRATION};

uint8_t es_pollen_concentration_char_val[3] = {0};

uint16_t es_pollen_concentration_char_cccd = 0;

/* Characteristic ( Environmental Sensing: Rainfall ) */
static const struct atts_char_desc es_rainfall_char = {
	RBLE_GATT_CHAR_PROP_NTF | RBLE_GATT_CHAR_PROP_RD,
	{(uint8_t)(ENVIRONMENTAL_SENSING_HDL_ES_RAINFALL_VAL & 0xff),(uint8_t)((ENVIRONMENTAL_SENSING_HDL_ES_RAINFALL_VAL >> 8) & 0xff)},
	RBLE_BDS_CHAR_ES_RAINFALL};

uint16_t es_rainfall_char_val = 0;

uint16_t es_rainfall_char_cccd = 0;

/* Characteristic ( Environmental Sensing: Pressure ) */
static const struct atts_char_desc es_pressure_char = {
	RBLE_GATT_CHAR_PROP_NTF | RBLE_GATT_CHAR_PROP_RD,
	{(uint8_t)(ENVIRONMENTAL_SENSING_HDL_ES_PRESSURE_VAL & 0xff),(uint8_t)((ENVIRONMENTAL_SENSING_HDL_ES_PRESSURE_VAL >> 8) & 0xff)},
	RBLE_BDS_CHAR_ES_PRESSURE};

uint32_t es_pressure_char_val = 0;

uint16_t es_pressure_char_cccd = 0;

/* Characteristic ( Environmental Sensing: Temperature ) */
static const struct atts_char_desc es_temperature_char = {
	RBLE_GATT_CHAR_PROP_NTF | RBLE_GATT_CHAR_PROP_RD,
	{(uint8_t)(ENVIRONMENTAL_SENSING_HDL_ES_TEMPERATURE_VAL & 0xff),(uint8_t)((ENVIRONMENTAL_SENSING_HDL_ES_TEMPERATURE_VAL >> 8) & 0xff)},
	RBLE_BDS_CHAR_ES_TEMPERATURE};

int16_t es_temperature_char_val = 0;

uint16_t es_temperature_char_cccd = 0;

/* Characteristic ( Environmental Sensing: True Wind Direction ) */
static const struct atts_char_desc es_true_wind_direction_char = {
	RBLE_GATT_CHAR_PROP_NTF | RBLE_GATT_CHAR_PROP_RD,
	{(uint8_t)(ENVIRONMENTAL_SENSING_HDL_ES_TRUE_WIND_DIRECTION_VAL & 0xff),(uint8_t)((ENVIRONMENTAL_SENSING_HDL_ES_TRUE_WIND_DIRECTION_VAL >> 8) & 0xff)},
	RBLE_BDS_CHAR_ES_TRUE_WIND_DIRECTION};

uint16_t es_true_wind_direction_char_val = 0;

uint16_t es_true_wind_direction_char_cccd = 0;

/* Characteristic ( Environmental Sensing: True Wind Speed ) */
static const struct atts_char_desc es_true_wind_speed_char = {
	RBLE_GATT_CHAR_PROP_NTF | RBLE_GATT_CHAR_PROP_RD,
	{(uint8_t)(ENVIRONMENTAL_SENSING_HDL_ES_TRUE_WIND_SPEED_VAL & 0xff),(uint8_t)((ENVIRONMENTAL_SENSING_HDL_ES_TRUE_WIND_SPEED_VAL >> 8) & 0xff)},
	RBLE_BDS_CHAR_ES_TRUE_WIND_SPEED};

uint16_t es_true_wind_speed_char_val = 0;

uint16_t es_true_wind_speed_char_cccd = 0;

/* Characteristic ( Environmental Sensing: UV Index ) */
static const struct atts_char_desc es_uv_index_char = {
	RBLE_GATT_CHAR_PROP_NTF | RBLE_GATT_CHAR_PROP_RD,
	{(uint8_t)(ENVIRONMENTAL_SENSING_HDL_ES_UV_INDEX_VAL & 0xff),(uint8_t)((ENVIRONMENTAL_SENSING_HDL_ES_UV_INDEX_VAL >> 8) & 0xff)},
	RBLE_BDS_CHAR_ES_UV_INDEX};

uint8_t es_uv_index_char_val = 0;

uint16_t es_uv_index_char_cccd = 0;

/* Characteristic ( Environmental Sensing: Wind Chill ) */
static const struct atts_char_desc es_wind_chill_char = {
	RBLE_GATT_CHAR_PROP_NTF | RBLE_GATT_CHAR_PROP_RD,
	{(uint8_t)(ENVIRONMENTAL_SENSING_HDL_ES_WIND_CHILL_VAL & 0xff),(uint8_t)((ENVIRONMENTAL_SENSING_HDL_ES_WIND_CHILL_VAL >> 8) & 0xff)},
	RBLE_BDS_CHAR_ES_WIND_CHILL};

int8_t es_wind_chill_char_val = 0;

uint16_t es_wind_chill_char_cccd = 0;

/* Characteristic ( Environmental Sensing: Barometric Pressure Trend ) */
static const struct atts_char_desc es_barometric_pressure_trend_char = {
	RBLE_GATT_CHAR_PROP_NTF | RBLE_GATT_CHAR_PROP_RD,
	{(uint8_t)(ENVIRONMENTAL_SENSING_HDL_ES_BAROMETRIC_PRESSURE_TREND_VAL & 0xff),(uint8_t)((ENVIRONMENTAL_SENSING_HDL_ES_BAROMETRIC_PRESSURE_TREND_VAL >> 8) & 0xff)},
	RBLE_BDS_CHAR_ES_BAROMETRIC_PRESSURE_TREND};

uint8_t es_barometric_pressure_trend_char_val = 0;

uint16_t es_barometric_pressure_trend_char_cccd = 0;

/* Characteristic ( Environmental Sensing: Magnetic Declination ) */
static const struct atts_char_desc es_magnetic_declination_char = {
	RBLE_GATT_CHAR_PROP_NTF | RBLE_GATT_CHAR_PROP_RD,
	{(uint8_t)(ENVIRONMENTAL_SENSING_HDL_ES_MAGNETIC_DECLINATION_VAL & 0xff),(uint8_t)((ENVIRONMENTAL_SENSING_HDL_ES_MAGNETIC_DECLINATION_VAL >> 8) & 0xff)},
	RBLE_BDS_CHAR_ES_MAGNETIC_DECLINATION};

uint16_t es_magnetic_declination_char_val = 0;

uint16_t es_magnetic_declination_char_cccd = 0;

/* Characteristic ( Environmental Sensing: Magnetic Flux Density - 2D ) */
static const struct atts_char_desc es_magnetic_flux_density___2d_char = {
	RBLE_GATT_CHAR_PROP_NTF | RBLE_GATT_CHAR_PROP_RD,
	{(uint8_t)(ENVIRONMENTAL_SENSING_HDL_ES_MAGNETIC_FLUX_DENSITY___2D_VAL & 0xff),(uint8_t)((ENVIRONMENTAL_SENSING_HDL_ES_MAGNETIC_FLUX_DENSITY___2D_VAL >> 8) & 0xff)},
	RBLE_BDS_CHAR_ES_MAGNETIC_FLUX_DENSITY___2D};

struct st_es_magnetic_flux_density___2d_char_val
{
	int16_t magnetic_flux_density__x_axis;
	int16_t magnetic_flux_density__y_axis;
} es_magnetic_flux_density___2d_char_val = { 0, 0 };

uint16_t es_magnetic_flux_density___2d_char_cccd = 0;

/* Characteristic ( Environmental Sensing: Magnetic Flux Density - 3D ) */
static const struct atts_char_desc es_magnetic_flux_density___3d_char = {
	RBLE_GATT_CHAR_PROP_NTF | RBLE_GATT_CHAR_PROP_RD,
	{(uint8_t)(ENVIRONMENTAL_SENSING_HDL_ES_MAGNETIC_FLUX_DENSITY___3D_VAL & 0xff),(uint8_t)((ENVIRONMENTAL_SENSING_HDL_ES_MAGNETIC_FLUX_DENSITY___3D_VAL >> 8) & 0xff)},
	RBLE_BDS_CHAR_ES_MAGNETIC_FLUX_DENSITY___3D};

struct st_es_magnetic_flux_density___3d_char_val
{
	int16_t magnetic_flux_density__x_axis;
	int16_t magnetic_flux_density__y_axis;
	int16_t magnetic_flux_density__z_axis;
} es_magnetic_flux_density___3d_char_val = { 0, 0, 0 };

uint16_t es_magnetic_flux_density___3d_char_cccd = 0;


/* Service ( Device Information ) */
static const uint8_t device_information_svc[RBLE_GATT_16BIT_UUID_OCTET] = RBLE_BDS_SVC_DEVICE_INFORMATION;

/* Characteristic ( Device Information: Manufacturer Name String ) */
static const struct atts_char_desc di_manufacturer_name_string_char = {
	RBLE_GATT_CHAR_PROP_RD,
	{(uint8_t)(ENVIRONMENTAL_SENSING_HDL_DI_MANUFACTURER_NAME_STRING_VAL & 0xff),(uint8_t)((ENVIRONMENTAL_SENSING_HDL_DI_MANUFACTURER_NAME_STRING_VAL >> 8) & 0xff)},
	RBLE_BDS_CHAR_DI_MANUFACTURER_NAME_STRING};

uint8_t di_manufacturer_name_string_char_val[] = "Sample";

/* Characteristic ( Device Information: Model Number String ) */
static const struct atts_char_desc di_model_number_string_char = {
	RBLE_GATT_CHAR_PROP_RD,
	{(uint8_t)(ENVIRONMENTAL_SENSING_HDL_DI_MODEL_NUMBER_STRING_VAL & 0xff),(uint8_t)((ENVIRONMENTAL_SENSING_HDL_DI_MODEL_NUMBER_STRING_VAL >> 8) & 0xff)},
	RBLE_BDS_CHAR_DI_MODEL_NUMBER_STRING};

uint8_t di_model_number_string_char_val[] = "Sample";

/* Characteristic ( Device Information: Serial Number String ) */
static const struct atts_char_desc di_serial_number_string_char = {
	RBLE_GATT_CHAR_PROP_RD,
	{(uint8_t)(ENVIRONMENTAL_SENSING_HDL_DI_SERIAL_NUMBER_STRING_VAL & 0xff),(uint8_t)((ENVIRONMENTAL_SENSING_HDL_DI_SERIAL_NUMBER_STRING_VAL >> 8) & 0xff)},
	RBLE_BDS_CHAR_DI_SERIAL_NUMBER_STRING};

uint8_t di_serial_number_string_char_val[] = "Sample";

/* Characteristic ( Device Information: Hardware Revision String ) */
static const struct atts_char_desc di_hardware_revision_string_char = {
	RBLE_GATT_CHAR_PROP_RD,
	{(uint8_t)(ENVIRONMENTAL_SENSING_HDL_DI_HARDWARE_REVISION_STRING_VAL & 0xff),(uint8_t)((ENVIRONMENTAL_SENSING_HDL_DI_HARDWARE_REVISION_STRING_VAL >> 8) & 0xff)},
	RBLE_BDS_CHAR_DI_HARDWARE_REVISION_STRING};

uint8_t di_hardware_revision_string_char_val[] = "Sample";

/* Characteristic ( Device Information: Firmware Revision String ) */
static const struct atts_char_desc di_firmware_revision_string_char = {
	RBLE_GATT_CHAR_PROP_RD,
	{(uint8_t)(ENVIRONMENTAL_SENSING_HDL_DI_FIRMWARE_REVISION_STRING_VAL & 0xff),(uint8_t)((ENVIRONMENTAL_SENSING_HDL_DI_FIRMWARE_REVISION_STRING_VAL >> 8) & 0xff)},
	RBLE_BDS_CHAR_DI_FIRMWARE_REVISION_STRING};

uint8_t di_firmware_revision_string_char_val[] = "Sample";

/* Characteristic ( Device Information: Software Revision String ) */
static const struct atts_char_desc di_software_revision_string_char = {
	RBLE_GATT_CHAR_PROP_RD,
	{(uint8_t)(ENVIRONMENTAL_SENSING_HDL_DI_SOFTWARE_REVISION_STRING_VAL & 0xff),(uint8_t)((ENVIRONMENTAL_SENSING_HDL_DI_SOFTWARE_REVISION_STRING_VAL >> 8) & 0xff)},
	RBLE_BDS_CHAR_DI_SOFTWARE_REVISION_STRING};

uint8_t di_software_revision_string_char_val[] = "Sample";

/* Characteristic ( Device Information: System ID ) */
static const struct atts_char_desc di_system_id_char = {
	RBLE_GATT_CHAR_PROP_RD,
	{(uint8_t)(ENVIRONMENTAL_SENSING_HDL_DI_SYSTEM_ID_VAL & 0xff),(uint8_t)((ENVIRONMENTAL_SENSING_HDL_DI_SYSTEM_ID_VAL >> 8) & 0xff)},
	RBLE_BDS_CHAR_DI_SYSTEM_ID};

struct st_di_system_id_char_val
{
	uint8_t manufacturer_identifier[5];
	uint8_t organizationally_unique_identifier[3];
} di_system_id_char_val = { {0}, {0} };

/* Characteristic ( Device Information: IEEE 11073-20601 Regulatory Certification Data List ) */
static const struct atts_char_desc di_ieee_11073_20601_regulatory_certification_data_list_char = {
	RBLE_GATT_CHAR_PROP_RD,
	{(uint8_t)(ENVIRONMENTAL_SENSING_HDL_DI_IEEE_11073_20601_REGULATORY_CERTIFICATION_DATA_LIST_VAL & 0xff),(uint8_t)((ENVIRONMENTAL_SENSING_HDL_DI_IEEE_11073_20601_REGULATORY_CERTIFICATION_DATA_LIST_VAL >> 8) & 0xff)},
	RBLE_BDS_CHAR_DI_IEEE_11073_20601_REGULATORY_CERTIFICATION_DATA_LIST};

uint8_t di_ieee_11073_20601_regulatory_certification_data_list_char_val[6] = {0};

/* Characteristic ( Device Information: PnP ID ) */
static const struct atts_char_desc di_pnp_id_char = {
	RBLE_GATT_CHAR_PROP_RD,
	{(uint8_t)(ENVIRONMENTAL_SENSING_HDL_DI_PNP_ID_VAL & 0xff),(uint8_t)((ENVIRONMENTAL_SENSING_HDL_DI_PNP_ID_VAL >> 8) & 0xff)},
	RBLE_BDS_CHAR_DI_PNP_ID};

struct st_di_pnp_id_char_val
{
	uint8_t vendor_id_source;
	uint16_t vendor_id;
	uint16_t product_id;
	uint16_t product_version;
} di_pnp_id_char_val = { 0, 0, 0, 0 };


/* Service ( Battery Service ) */
static const uint8_t battery_service_svc[RBLE_GATT_16BIT_UUID_OCTET] = RBLE_BDS_SVC_BATTERY_SERVICE;

/* Characteristic ( Battery Service: Battery Level ) */
static const struct atts_char_desc bs_battery_level_char = {
	RBLE_GATT_CHAR_PROP_NTF | RBLE_GATT_CHAR_PROP_RD,
	{(uint8_t)(ENVIRONMENTAL_SENSING_HDL_BS_BATTERY_LEVEL_VAL & 0xff),(uint8_t)((ENVIRONMENTAL_SENSING_HDL_BS_BATTERY_LEVEL_VAL >> 8) & 0xff)},
	RBLE_BDS_CHAR_BS_BATTERY_LEVEL};

uint8_t bs_battery_level_char_val = 0;

uint16_t bs_battery_level_char_cccd = 0;



#endif /* #if USE_SAMPLE_PROFILE */

/** Attribute Database */
const struct atts_desc atts_desc_list_prf[] =
{
    #if (USE_SAMPLE_PROFILE)
    /*********************************
     * Sample Custom Service         *
     *********************************/
	/* Service ( Environmental Sensing ) */
	{ RBLE_DECL_PRIMARY_SERVICE, 
		sizeof(environmental_sensing_svc),	sizeof(environmental_sensing_svc),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_SVC_ENVIRONMENTAL_SENSING),	RBLE_GATT_PERM_RD,	(void *)&environmental_sensing_svc},
	/* Characteristic ( Environmental Sensing: Descriptor Value Changed ) */
	{ RBLE_DECL_CHARACTERISTIC, 
		sizeof(es_descriptor_value_changed_char),	sizeof(es_descriptor_value_changed_char),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_ES_DESCRIPTOR_VALUE_CHANGED_CHAR), 	RBLE_GATT_PERM_RD,	(void *)&es_descriptor_value_changed_char},
	{ 0x2A7D, 
		sizeof(es_descriptor_value_changed_char_val),	sizeof(es_descriptor_value_changed_char_val),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_ES_DESCRIPTOR_VALUE_CHANGED_VAL), 	( RBLE_GATT_PERM_NI ),	(void *)&es_descriptor_value_changed_char_val},
	{ RBLE_DESC_CLIENT_CHAR_CONF, 
		sizeof(es_descriptor_value_changed_char_cccd),	sizeof(es_descriptor_value_changed_char_cccd),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_ES_DESCRIPTOR_VALUE_CHANGED_CCCD), 	(RBLE_GATT_PERM_RD|RBLE_GATT_PERM_WR),	(void *)&es_descriptor_value_changed_char_cccd},
	/* Characteristic ( Environmental Sensing: Apparent Wind Direction ) */
	{ RBLE_DECL_CHARACTERISTIC, 
		sizeof(es_apparent_wind_direction_char),	sizeof(es_apparent_wind_direction_char),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_ES_APPARENT_WIND_DIRECTION_CHAR), 	RBLE_GATT_PERM_RD,	(void *)&es_apparent_wind_direction_char},
	{ 0x2A73, 
		sizeof(es_apparent_wind_direction_char_val),	sizeof(es_apparent_wind_direction_char_val),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_ES_APPARENT_WIND_DIRECTION_VAL), 	( RBLE_GATT_PERM_NI| RBLE_GATT_PERM_NOTIFY_COMP_EN | RBLE_GATT_PERM_RD ),	(void *)&es_apparent_wind_direction_char_val},
	{ RBLE_DESC_CLIENT_CHAR_CONF, 
		sizeof(es_apparent_wind_direction_char_cccd),	sizeof(es_apparent_wind_direction_char_cccd),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_ES_APPARENT_WIND_DIRECTION_CCCD), 	(RBLE_GATT_PERM_RD|RBLE_GATT_PERM_WR),	(void *)&es_apparent_wind_direction_char_cccd},
	/* Characteristic ( Environmental Sensing: Apparent Wind Speed ) */
	{ RBLE_DECL_CHARACTERISTIC, 
		sizeof(es_apparent_wind_speed_char),	sizeof(es_apparent_wind_speed_char),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_ES_APPARENT_WIND_SPEED_CHAR), 	RBLE_GATT_PERM_RD,	(void *)&es_apparent_wind_speed_char},
	{ 0x2A72, 
		sizeof(es_apparent_wind_speed_char_val),	sizeof(es_apparent_wind_speed_char_val),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_ES_APPARENT_WIND_SPEED_VAL), 	( RBLE_GATT_PERM_NI| RBLE_GATT_PERM_NOTIFY_COMP_EN | RBLE_GATT_PERM_RD ),	(void *)&es_apparent_wind_speed_char_val},
	{ RBLE_DESC_CLIENT_CHAR_CONF, 
		sizeof(es_apparent_wind_speed_char_cccd),	sizeof(es_apparent_wind_speed_char_cccd),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_ES_APPARENT_WIND_SPEED_CCCD), 	(RBLE_GATT_PERM_RD|RBLE_GATT_PERM_WR),	(void *)&es_apparent_wind_speed_char_cccd},
	/* Characteristic ( Environmental Sensing: Dew Point ) */
	{ RBLE_DECL_CHARACTERISTIC, 
		sizeof(es_dew_point_char),	sizeof(es_dew_point_char),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_ES_DEW_POINT_CHAR), 	RBLE_GATT_PERM_RD,	(void *)&es_dew_point_char},
	{ 0x2A7B, 
		sizeof(es_dew_point_char_val),	sizeof(es_dew_point_char_val),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_ES_DEW_POINT_VAL), 	( RBLE_GATT_PERM_NI| RBLE_GATT_PERM_NOTIFY_COMP_EN | RBLE_GATT_PERM_RD ),	(void *)&es_dew_point_char_val},
	{ RBLE_DESC_CLIENT_CHAR_CONF, 
		sizeof(es_dew_point_char_cccd),	sizeof(es_dew_point_char_cccd),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_ES_DEW_POINT_CCCD), 	(RBLE_GATT_PERM_RD|RBLE_GATT_PERM_WR),	(void *)&es_dew_point_char_cccd},
	/* Characteristic ( Environmental Sensing: Elevation ) */
	{ RBLE_DECL_CHARACTERISTIC, 
		sizeof(es_elevation_char),	sizeof(es_elevation_char),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_ES_ELEVATION_CHAR), 	RBLE_GATT_PERM_RD,	(void *)&es_elevation_char},
	{ 0x2A6C, 
		sizeof(es_elevation_char_val),	sizeof(es_elevation_char_val),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_ES_ELEVATION_VAL), 	( RBLE_GATT_PERM_NI| RBLE_GATT_PERM_NOTIFY_COMP_EN | RBLE_GATT_PERM_RD ),	(void *)&es_elevation_char_val},
	{ RBLE_DESC_CLIENT_CHAR_CONF, 
		sizeof(es_elevation_char_cccd),	sizeof(es_elevation_char_cccd),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_ES_ELEVATION_CCCD), 	(RBLE_GATT_PERM_RD|RBLE_GATT_PERM_WR),	(void *)&es_elevation_char_cccd},
	/* Characteristic ( Environmental Sensing: Gust Factor ) */
	{ RBLE_DECL_CHARACTERISTIC, 
		sizeof(es_gust_factor_char),	sizeof(es_gust_factor_char),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_ES_GUST_FACTOR_CHAR), 	RBLE_GATT_PERM_RD,	(void *)&es_gust_factor_char},
	{ 0x2A74, 
		sizeof(es_gust_factor_char_val),	sizeof(es_gust_factor_char_val),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_ES_GUST_FACTOR_VAL), 	( RBLE_GATT_PERM_NI| RBLE_GATT_PERM_NOTIFY_COMP_EN | RBLE_GATT_PERM_RD ),	(void *)&es_gust_factor_char_val},
	{ RBLE_DESC_CLIENT_CHAR_CONF, 
		sizeof(es_gust_factor_char_cccd),	sizeof(es_gust_factor_char_cccd),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_ES_GUST_FACTOR_CCCD), 	(RBLE_GATT_PERM_RD|RBLE_GATT_PERM_WR),	(void *)&es_gust_factor_char_cccd},
	/* Characteristic ( Environmental Sensing: Heat Index ) */
	{ RBLE_DECL_CHARACTERISTIC, 
		sizeof(es_heat_index_char),	sizeof(es_heat_index_char),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_ES_HEAT_INDEX_CHAR), 	RBLE_GATT_PERM_RD,	(void *)&es_heat_index_char},
	{ 0x2A7A, 
		sizeof(es_heat_index_char_val),	sizeof(es_heat_index_char_val),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_ES_HEAT_INDEX_VAL), 	( RBLE_GATT_PERM_NI| RBLE_GATT_PERM_NOTIFY_COMP_EN | RBLE_GATT_PERM_RD ),	(void *)&es_heat_index_char_val},
	{ RBLE_DESC_CLIENT_CHAR_CONF, 
		sizeof(es_heat_index_char_cccd),	sizeof(es_heat_index_char_cccd),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_ES_HEAT_INDEX_CCCD), 	(RBLE_GATT_PERM_RD|RBLE_GATT_PERM_WR),	(void *)&es_heat_index_char_cccd},
	/* Characteristic ( Environmental Sensing: Humidity ) */
	{ RBLE_DECL_CHARACTERISTIC, 
		sizeof(es_humidity_char),	sizeof(es_humidity_char),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_ES_HUMIDITY_CHAR), 	RBLE_GATT_PERM_RD,	(void *)&es_humidity_char},
	{ 0x2A6F, 
		sizeof(es_humidity_char_val),	sizeof(es_humidity_char_val),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_ES_HUMIDITY_VAL), 	( RBLE_GATT_PERM_NI| RBLE_GATT_PERM_NOTIFY_COMP_EN | RBLE_GATT_PERM_RD ),	(void *)&es_humidity_char_val},
	{ RBLE_DESC_CLIENT_CHAR_CONF, 
		sizeof(es_humidity_char_cccd),	sizeof(es_humidity_char_cccd),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_ES_HUMIDITY_CCCD), 	(RBLE_GATT_PERM_RD|RBLE_GATT_PERM_WR),	(void *)&es_humidity_char_cccd},
	/* Characteristic ( Environmental Sensing: Irradiance ) */
	{ RBLE_DECL_CHARACTERISTIC, 
		sizeof(es_irradiance_char),	sizeof(es_irradiance_char),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_ES_IRRADIANCE_CHAR), 	RBLE_GATT_PERM_RD,	(void *)&es_irradiance_char},
	{ 0x2A77, 
		sizeof(es_irradiance_char_val),	sizeof(es_irradiance_char_val),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_ES_IRRADIANCE_VAL), 	( RBLE_GATT_PERM_NI| RBLE_GATT_PERM_NOTIFY_COMP_EN | RBLE_GATT_PERM_RD ),	(void *)&es_irradiance_char_val},
	{ RBLE_DESC_CLIENT_CHAR_CONF, 
		sizeof(es_irradiance_char_cccd),	sizeof(es_irradiance_char_cccd),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_ES_IRRADIANCE_CCCD), 	(RBLE_GATT_PERM_RD|RBLE_GATT_PERM_WR),	(void *)&es_irradiance_char_cccd},
	/* Characteristic ( Environmental Sensing: Pollen Concentration ) */
	{ RBLE_DECL_CHARACTERISTIC, 
		sizeof(es_pollen_concentration_char),	sizeof(es_pollen_concentration_char),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_ES_POLLEN_CONCENTRATION_CHAR), 	RBLE_GATT_PERM_RD,	(void *)&es_pollen_concentration_char},
	{ 0x2A75, 
		sizeof(es_pollen_concentration_char_val),	sizeof(es_pollen_concentration_char_val),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_ES_POLLEN_CONCENTRATION_VAL), 	( RBLE_GATT_PERM_NI| RBLE_GATT_PERM_NOTIFY_COMP_EN | RBLE_GATT_PERM_RD ),	(void *)&es_pollen_concentration_char_val},
	{ RBLE_DESC_CLIENT_CHAR_CONF, 
		sizeof(es_pollen_concentration_char_cccd),	sizeof(es_pollen_concentration_char_cccd),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_ES_POLLEN_CONCENTRATION_CCCD), 	(RBLE_GATT_PERM_RD|RBLE_GATT_PERM_WR),	(void *)&es_pollen_concentration_char_cccd},
	/* Characteristic ( Environmental Sensing: Rainfall ) */
	{ RBLE_DECL_CHARACTERISTIC, 
		sizeof(es_rainfall_char),	sizeof(es_rainfall_char),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_ES_RAINFALL_CHAR), 	RBLE_GATT_PERM_RD,	(void *)&es_rainfall_char},
	{ 0x2A78, 
		sizeof(es_rainfall_char_val),	sizeof(es_rainfall_char_val),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_ES_RAINFALL_VAL), 	( RBLE_GATT_PERM_NI| RBLE_GATT_PERM_NOTIFY_COMP_EN | RBLE_GATT_PERM_RD ),	(void *)&es_rainfall_char_val},
	{ RBLE_DESC_CLIENT_CHAR_CONF, 
		sizeof(es_rainfall_char_cccd),	sizeof(es_rainfall_char_cccd),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_ES_RAINFALL_CCCD), 	(RBLE_GATT_PERM_RD|RBLE_GATT_PERM_WR),	(void *)&es_rainfall_char_cccd},
	/* Characteristic ( Environmental Sensing: Pressure ) */
	{ RBLE_DECL_CHARACTERISTIC, 
		sizeof(es_pressure_char),	sizeof(es_pressure_char),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_ES_PRESSURE_CHAR), 	RBLE_GATT_PERM_RD,	(void *)&es_pressure_char},
	{ 0x2A6D, 
		sizeof(es_pressure_char_val),	sizeof(es_pressure_char_val),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_ES_PRESSURE_VAL), 	( RBLE_GATT_PERM_NI| RBLE_GATT_PERM_NOTIFY_COMP_EN | RBLE_GATT_PERM_RD ),	(void *)&es_pressure_char_val},
	{ RBLE_DESC_CLIENT_CHAR_CONF, 
		sizeof(es_pressure_char_cccd),	sizeof(es_pressure_char_cccd),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_ES_PRESSURE_CCCD), 	(RBLE_GATT_PERM_RD|RBLE_GATT_PERM_WR),	(void *)&es_pressure_char_cccd},
	/* Characteristic ( Environmental Sensing: Temperature ) */
	{ RBLE_DECL_CHARACTERISTIC, 
		sizeof(es_temperature_char),	sizeof(es_temperature_char),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_ES_TEMPERATURE_CHAR), 	RBLE_GATT_PERM_RD,	(void *)&es_temperature_char},
	{ 0x2A6E, 
		sizeof(es_temperature_char_val),	sizeof(es_temperature_char_val),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_ES_TEMPERATURE_VAL), 	( RBLE_GATT_PERM_NI| RBLE_GATT_PERM_NOTIFY_COMP_EN | RBLE_GATT_PERM_RD ),	(void *)&es_temperature_char_val},
	{ RBLE_DESC_CLIENT_CHAR_CONF, 
		sizeof(es_temperature_char_cccd),	sizeof(es_temperature_char_cccd),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_ES_TEMPERATURE_CCCD), 	(RBLE_GATT_PERM_RD|RBLE_GATT_PERM_WR),	(void *)&es_temperature_char_cccd},
	/* Characteristic ( Environmental Sensing: True Wind Direction ) */
	{ RBLE_DECL_CHARACTERISTIC, 
		sizeof(es_true_wind_direction_char),	sizeof(es_true_wind_direction_char),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_ES_TRUE_WIND_DIRECTION_CHAR), 	RBLE_GATT_PERM_RD,	(void *)&es_true_wind_direction_char},
	{ 0x2A71, 
		sizeof(es_true_wind_direction_char_val),	sizeof(es_true_wind_direction_char_val),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_ES_TRUE_WIND_DIRECTION_VAL), 	( RBLE_GATT_PERM_NI| RBLE_GATT_PERM_NOTIFY_COMP_EN | RBLE_GATT_PERM_RD ),	(void *)&es_true_wind_direction_char_val},
	{ RBLE_DESC_CLIENT_CHAR_CONF, 
		sizeof(es_true_wind_direction_char_cccd),	sizeof(es_true_wind_direction_char_cccd),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_ES_TRUE_WIND_DIRECTION_CCCD), 	(RBLE_GATT_PERM_RD|RBLE_GATT_PERM_WR),	(void *)&es_true_wind_direction_char_cccd},
	/* Characteristic ( Environmental Sensing: True Wind Speed ) */
	{ RBLE_DECL_CHARACTERISTIC, 
		sizeof(es_true_wind_speed_char),	sizeof(es_true_wind_speed_char),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_ES_TRUE_WIND_SPEED_CHAR), 	RBLE_GATT_PERM_RD,	(void *)&es_true_wind_speed_char},
	{ 0x2A70, 
		sizeof(es_true_wind_speed_char_val),	sizeof(es_true_wind_speed_char_val),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_ES_TRUE_WIND_SPEED_VAL), 	( RBLE_GATT_PERM_NI| RBLE_GATT_PERM_NOTIFY_COMP_EN | RBLE_GATT_PERM_RD ),	(void *)&es_true_wind_speed_char_val},
	{ RBLE_DESC_CLIENT_CHAR_CONF, 
		sizeof(es_true_wind_speed_char_cccd),	sizeof(es_true_wind_speed_char_cccd),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_ES_TRUE_WIND_SPEED_CCCD), 	(RBLE_GATT_PERM_RD|RBLE_GATT_PERM_WR),	(void *)&es_true_wind_speed_char_cccd},
	/* Characteristic ( Environmental Sensing: UV Index ) */
	{ RBLE_DECL_CHARACTERISTIC, 
		sizeof(es_uv_index_char),	sizeof(es_uv_index_char),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_ES_UV_INDEX_CHAR), 	RBLE_GATT_PERM_RD,	(void *)&es_uv_index_char},
	{ 0x2A76, 
		sizeof(es_uv_index_char_val),	sizeof(es_uv_index_char_val),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_ES_UV_INDEX_VAL), 	( RBLE_GATT_PERM_NI| RBLE_GATT_PERM_NOTIFY_COMP_EN | RBLE_GATT_PERM_RD ),	(void *)&es_uv_index_char_val},
	{ RBLE_DESC_CLIENT_CHAR_CONF, 
		sizeof(es_uv_index_char_cccd),	sizeof(es_uv_index_char_cccd),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_ES_UV_INDEX_CCCD), 	(RBLE_GATT_PERM_RD|RBLE_GATT_PERM_WR),	(void *)&es_uv_index_char_cccd},
	/* Characteristic ( Environmental Sensing: Wind Chill ) */
	{ RBLE_DECL_CHARACTERISTIC, 
		sizeof(es_wind_chill_char),	sizeof(es_wind_chill_char),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_ES_WIND_CHILL_CHAR), 	RBLE_GATT_PERM_RD,	(void *)&es_wind_chill_char},
	{ 0x2A79, 
		sizeof(es_wind_chill_char_val),	sizeof(es_wind_chill_char_val),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_ES_WIND_CHILL_VAL), 	( RBLE_GATT_PERM_NI| RBLE_GATT_PERM_NOTIFY_COMP_EN | RBLE_GATT_PERM_RD ),	(void *)&es_wind_chill_char_val},
	{ RBLE_DESC_CLIENT_CHAR_CONF, 
		sizeof(es_wind_chill_char_cccd),	sizeof(es_wind_chill_char_cccd),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_ES_WIND_CHILL_CCCD), 	(RBLE_GATT_PERM_RD|RBLE_GATT_PERM_WR),	(void *)&es_wind_chill_char_cccd},
	/* Characteristic ( Environmental Sensing: Barometric Pressure Trend ) */
	{ RBLE_DECL_CHARACTERISTIC, 
		sizeof(es_barometric_pressure_trend_char),	sizeof(es_barometric_pressure_trend_char),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_ES_BAROMETRIC_PRESSURE_TREND_CHAR), 	RBLE_GATT_PERM_RD,	(void *)&es_barometric_pressure_trend_char},
	{ 0x2AA3, 
		sizeof(es_barometric_pressure_trend_char_val),	sizeof(es_barometric_pressure_trend_char_val),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_ES_BAROMETRIC_PRESSURE_TREND_VAL), 	( RBLE_GATT_PERM_NI| RBLE_GATT_PERM_NOTIFY_COMP_EN | RBLE_GATT_PERM_RD ),	(void *)&es_barometric_pressure_trend_char_val},
	{ RBLE_DESC_CLIENT_CHAR_CONF, 
		sizeof(es_barometric_pressure_trend_char_cccd),	sizeof(es_barometric_pressure_trend_char_cccd),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_ES_BAROMETRIC_PRESSURE_TREND_CCCD), 	(RBLE_GATT_PERM_RD|RBLE_GATT_PERM_WR),	(void *)&es_barometric_pressure_trend_char_cccd},
	/* Characteristic ( Environmental Sensing: Magnetic Declination ) */
	{ RBLE_DECL_CHARACTERISTIC, 
		sizeof(es_magnetic_declination_char),	sizeof(es_magnetic_declination_char),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_ES_MAGNETIC_DECLINATION_CHAR), 	RBLE_GATT_PERM_RD,	(void *)&es_magnetic_declination_char},
	{ 0x2A2C, 
		sizeof(es_magnetic_declination_char_val),	sizeof(es_magnetic_declination_char_val),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_ES_MAGNETIC_DECLINATION_VAL), 	( RBLE_GATT_PERM_NI| RBLE_GATT_PERM_NOTIFY_COMP_EN | RBLE_GATT_PERM_RD ),	(void *)&es_magnetic_declination_char_val},
	{ RBLE_DESC_CLIENT_CHAR_CONF, 
		sizeof(es_magnetic_declination_char_cccd),	sizeof(es_magnetic_declination_char_cccd),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_ES_MAGNETIC_DECLINATION_CCCD), 	(RBLE_GATT_PERM_RD|RBLE_GATT_PERM_WR),	(void *)&es_magnetic_declination_char_cccd},
	/* Characteristic ( Environmental Sensing: Magnetic Flux Density - 2D ) */
	{ RBLE_DECL_CHARACTERISTIC, 
		sizeof(es_magnetic_flux_density___2d_char),	sizeof(es_magnetic_flux_density___2d_char),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_ES_MAGNETIC_FLUX_DENSITY___2D_CHAR), 	RBLE_GATT_PERM_RD,	(void *)&es_magnetic_flux_density___2d_char},
	{ 0x2AA0, 
		sizeof(es_magnetic_flux_density___2d_char_val),	sizeof(es_magnetic_flux_density___2d_char_val),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_ES_MAGNETIC_FLUX_DENSITY___2D_VAL), 	( RBLE_GATT_PERM_NI| RBLE_GATT_PERM_NOTIFY_COMP_EN | RBLE_GATT_PERM_RD ),	(void *)&es_magnetic_flux_density___2d_char_val},
	{ RBLE_DESC_CLIENT_CHAR_CONF, 
		sizeof(es_magnetic_flux_density___2d_char_cccd),	sizeof(es_magnetic_flux_density___2d_char_cccd),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_ES_MAGNETIC_FLUX_DENSITY___2D_CCCD), 	(RBLE_GATT_PERM_RD|RBLE_GATT_PERM_WR),	(void *)&es_magnetic_flux_density___2d_char_cccd},
	/* Characteristic ( Environmental Sensing: Magnetic Flux Density - 3D ) */
	{ RBLE_DECL_CHARACTERISTIC, 
		sizeof(es_magnetic_flux_density___3d_char),	sizeof(es_magnetic_flux_density___3d_char),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_ES_MAGNETIC_FLUX_DENSITY___3D_CHAR), 	RBLE_GATT_PERM_RD,	(void *)&es_magnetic_flux_density___3d_char},
	{ 0x2AA1, 
		sizeof(es_magnetic_flux_density___3d_char_val),	sizeof(es_magnetic_flux_density___3d_char_val),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_ES_MAGNETIC_FLUX_DENSITY___3D_VAL), 	( RBLE_GATT_PERM_NI| RBLE_GATT_PERM_NOTIFY_COMP_EN | RBLE_GATT_PERM_RD ),	(void *)&es_magnetic_flux_density___3d_char_val},
	{ RBLE_DESC_CLIENT_CHAR_CONF, 
		sizeof(es_magnetic_flux_density___3d_char_cccd),	sizeof(es_magnetic_flux_density___3d_char_cccd),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_ES_MAGNETIC_FLUX_DENSITY___3D_CCCD), 	(RBLE_GATT_PERM_RD|RBLE_GATT_PERM_WR),	(void *)&es_magnetic_flux_density___3d_char_cccd},
	/* Service ( Device Information ) */
	{ RBLE_DECL_PRIMARY_SERVICE, 
		sizeof(device_information_svc),	sizeof(device_information_svc),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_SVC_DEVICE_INFORMATION),	RBLE_GATT_PERM_RD,	(void *)&device_information_svc},
	/* Characteristic ( Device Information: Manufacturer Name String ) */
	{ RBLE_DECL_CHARACTERISTIC, 
		sizeof(di_manufacturer_name_string_char),	sizeof(di_manufacturer_name_string_char),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_DI_MANUFACTURER_NAME_STRING_CHAR), 	RBLE_GATT_PERM_RD,	(void *)&di_manufacturer_name_string_char},
	{ 0x2A29, 
		sizeof(di_manufacturer_name_string_char_val),	sizeof(di_manufacturer_name_string_char_val),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_DI_MANUFACTURER_NAME_STRING_VAL), 	( RBLE_GATT_PERM_RD ),	(void *)&di_manufacturer_name_string_char_val},
	/* Characteristic ( Device Information: Model Number String ) */
	{ RBLE_DECL_CHARACTERISTIC, 
		sizeof(di_model_number_string_char),	sizeof(di_model_number_string_char),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_DI_MODEL_NUMBER_STRING_CHAR), 	RBLE_GATT_PERM_RD,	(void *)&di_model_number_string_char},
	{ 0x2A24, 
		sizeof(di_model_number_string_char_val),	sizeof(di_model_number_string_char_val),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_DI_MODEL_NUMBER_STRING_VAL), 	( RBLE_GATT_PERM_RD ),	(void *)&di_model_number_string_char_val},
	/* Characteristic ( Device Information: Serial Number String ) */
	{ RBLE_DECL_CHARACTERISTIC, 
		sizeof(di_serial_number_string_char),	sizeof(di_serial_number_string_char),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_DI_SERIAL_NUMBER_STRING_CHAR), 	RBLE_GATT_PERM_RD,	(void *)&di_serial_number_string_char},
	{ 0x2A25, 
		sizeof(di_serial_number_string_char_val),	sizeof(di_serial_number_string_char_val),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_DI_SERIAL_NUMBER_STRING_VAL), 	( RBLE_GATT_PERM_RD ),	(void *)&di_serial_number_string_char_val},
	/* Characteristic ( Device Information: Hardware Revision String ) */
	{ RBLE_DECL_CHARACTERISTIC, 
		sizeof(di_hardware_revision_string_char),	sizeof(di_hardware_revision_string_char),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_DI_HARDWARE_REVISION_STRING_CHAR), 	RBLE_GATT_PERM_RD,	(void *)&di_hardware_revision_string_char},
	{ 0x2A27, 
		sizeof(di_hardware_revision_string_char_val),	sizeof(di_hardware_revision_string_char_val),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_DI_HARDWARE_REVISION_STRING_VAL), 	( RBLE_GATT_PERM_RD ),	(void *)&di_hardware_revision_string_char_val},
	/* Characteristic ( Device Information: Firmware Revision String ) */
	{ RBLE_DECL_CHARACTERISTIC, 
		sizeof(di_firmware_revision_string_char),	sizeof(di_firmware_revision_string_char),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_DI_FIRMWARE_REVISION_STRING_CHAR), 	RBLE_GATT_PERM_RD,	(void *)&di_firmware_revision_string_char},
	{ 0x2A26, 
		sizeof(di_firmware_revision_string_char_val),	sizeof(di_firmware_revision_string_char_val),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_DI_FIRMWARE_REVISION_STRING_VAL), 	( RBLE_GATT_PERM_RD ),	(void *)&di_firmware_revision_string_char_val},
	/* Characteristic ( Device Information: Software Revision String ) */
	{ RBLE_DECL_CHARACTERISTIC, 
		sizeof(di_software_revision_string_char),	sizeof(di_software_revision_string_char),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_DI_SOFTWARE_REVISION_STRING_CHAR), 	RBLE_GATT_PERM_RD,	(void *)&di_software_revision_string_char},
	{ 0x2A28, 
		sizeof(di_software_revision_string_char_val),	sizeof(di_software_revision_string_char_val),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_DI_SOFTWARE_REVISION_STRING_VAL), 	( RBLE_GATT_PERM_RD ),	(void *)&di_software_revision_string_char_val},
	/* Characteristic ( Device Information: System ID ) */
	{ RBLE_DECL_CHARACTERISTIC, 
		sizeof(di_system_id_char),	sizeof(di_system_id_char),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_DI_SYSTEM_ID_CHAR), 	RBLE_GATT_PERM_RD,	(void *)&di_system_id_char},
	{ 0x2A23, 
		sizeof(di_system_id_char_val),	sizeof(di_system_id_char_val),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_DI_SYSTEM_ID_VAL), 	( RBLE_GATT_PERM_RD ),	(void *)&di_system_id_char_val},
	/* Characteristic ( Device Information: IEEE 11073-20601 Regulatory Certification Data List ) */
	{ RBLE_DECL_CHARACTERISTIC, 
		sizeof(di_ieee_11073_20601_regulatory_certification_data_list_char),	sizeof(di_ieee_11073_20601_regulatory_certification_data_list_char),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_DI_IEEE_11073_20601_REGULATORY_CERTIFICATION_DATA_LIST_CHAR), 	RBLE_GATT_PERM_RD,	(void *)&di_ieee_11073_20601_regulatory_certification_data_list_char},
	{ 0x2A2A, 
		sizeof(di_ieee_11073_20601_regulatory_certification_data_list_char_val),	sizeof(di_ieee_11073_20601_regulatory_certification_data_list_char_val),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_DI_IEEE_11073_20601_REGULATORY_CERTIFICATION_DATA_LIST_VAL), 	( RBLE_GATT_PERM_RD ),	(void *)&di_ieee_11073_20601_regulatory_certification_data_list_char_val},
	/* Characteristic ( Device Information: PnP ID ) */
	{ RBLE_DECL_CHARACTERISTIC, 
		sizeof(di_pnp_id_char),	sizeof(di_pnp_id_char),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_DI_PNP_ID_CHAR), 	RBLE_GATT_PERM_RD,	(void *)&di_pnp_id_char},
	{ 0x2A50, 
		sizeof(di_pnp_id_char_val),	sizeof(di_pnp_id_char_val),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_DI_PNP_ID_VAL), 	( RBLE_GATT_PERM_RD ),	(void *)&di_pnp_id_char_val},
	/* Service ( Battery Service ) */
	{ RBLE_DECL_PRIMARY_SERVICE, 
		sizeof(battery_service_svc),	sizeof(battery_service_svc),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_SVC_BATTERY_SERVICE),	RBLE_GATT_PERM_RD,	(void *)&battery_service_svc},
	/* Characteristic ( Battery Service: Battery Level ) */
	{ RBLE_DECL_CHARACTERISTIC, 
		sizeof(bs_battery_level_char),	sizeof(bs_battery_level_char),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_BS_BATTERY_LEVEL_CHAR), 	RBLE_GATT_PERM_RD,	(void *)&bs_battery_level_char},
	{ 0x2A19, 
		sizeof(bs_battery_level_char_val),	sizeof(bs_battery_level_char_val),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_BS_BATTERY_LEVEL_VAL), 	( RBLE_GATT_PERM_NI| RBLE_GATT_PERM_NOTIFY_COMP_EN | RBLE_GATT_PERM_RD ),	(void *)&bs_battery_level_char_val},
	{ RBLE_DESC_CLIENT_CHAR_CONF, 
		sizeof(bs_battery_level_char_cccd),	sizeof(bs_battery_level_char_cccd),	TASK_ATTID(TASK_RBLE, ENVIRONMENTAL_SENSING_IDX_BS_BATTERY_LEVEL_CCCD), 	(RBLE_GATT_PERM_RD|RBLE_GATT_PERM_WR),	(void *)&bs_battery_level_char_cccd},

    #endif /* #if (USE_SAMPLE_PROFILE) */
    /* Reserved */
    {0,0,0,0,0,0}
};

const uint16_t ATT_PRF_DB_SIZE = sizeof(atts_desc_list_prf);


