/**
 ****************************************************************************************
 *
 * @file        prf_sel.h
 *
 * @brief   Setting of Profile Selection
 *
 * Copyright(C) 2013-2017 Renesas Electronics Corporation
 *
 * This file is generated by Bluetooth Developer Studio plugin.
 *     BDS Version    : 1.1.3139.0
 *     Script Version : 2.0.1
 *
 ****************************************************************************************
 */

#ifndef _PRF_SEL_H_
#define _PRF_SEL_H_

/**
 * INCLUDE FILES
 ****************************************************************************************
 */

/**
 * TYPE DEFINES
 ****************************************************************************************
 */

/**
 * DEFINES
 ****************************************************************************************
 */
#ifdef USE_SAMPLE_PROFILE
#define USE_CUSTOM_DEMO
#endif

#define PXPM_TABLE_SIZE     0
#define PXPR_TABLE_SIZE     0
#define FMPL_TABLE_SIZE     0
#define FMPT_TABLE_SIZE     0
#define HTPC_TABLE_SIZE     0
#define HTPT_TABLE_SIZE     0
#define BLPC_TABLE_SIZE     0
#define BLPS_TABLE_SIZE     0
#define HGHD_TABLE_SIZE     0
#define HGBH_TABLE_SIZE     0
#define HGRH_TABLE_SIZE     0
#define SPPS_TABLE_SIZE     0
#define SPPC_TABLE_SIZE     0
#define HRPC_TABLE_SIZE     0
#define HRPS_TABLE_SIZE     0
#define CSCC_TABLE_SIZE     0
#define CSCS_TABLE_SIZE     0
#define GLPC_TABLE_SIZE     0
#define GLPS_TABLE_SIZE     0
#define CPPS_TABLE_SIZE     0
#define CPPC_TABLE_SIZE     0
#define TIPS_TABLE_SIZE     0
#define TIPC_TABLE_SIZE     0
#define ANPS_TABLE_SIZE     0
#define ANPC_TABLE_SIZE     0
#define LNPS_TABLE_SIZE     0
#define LNPC_TABLE_SIZE     0
#define PASS_TABLE_SIZE     0
#define PASC_TABLE_SIZE     0
#define RSCS_TABLE_SIZE     0
#define RSCC_TABLE_SIZE     0

#define HOST_TABLE_SIZE         88

#define GATT_DB_STRUCT_SIZE     6

#define RBLE_TABLE_SIZE  ((PXPM_TABLE_SIZE + PXPR_TABLE_SIZE + FMPL_TABLE_SIZE + FMPT_TABLE_SIZE \
                         + HTPC_TABLE_SIZE + HTPT_TABLE_SIZE + BLPC_TABLE_SIZE + BLPS_TABLE_SIZE \
                         + HGHD_TABLE_SIZE + HGBH_TABLE_SIZE + HGRH_TABLE_SIZE                   \
                         + SPPS_TABLE_SIZE + SPPC_TABLE_SIZE + HRPC_TABLE_SIZE + HRPS_TABLE_SIZE \
                         + CSCC_TABLE_SIZE + CSCS_TABLE_SIZE + GLPC_TABLE_SIZE + GLPS_TABLE_SIZE \
                         + CPPS_TABLE_SIZE + CPPC_TABLE_SIZE + TIPS_TABLE_SIZE + TIPC_TABLE_SIZE \
                         + ANPS_TABLE_SIZE + ANPC_TABLE_SIZE + LNPS_TABLE_SIZE + LNPC_TABLE_SIZE \
                         + PASS_TABLE_SIZE + PASC_TABLE_SIZE + RSCS_TABLE_SIZE + RSCC_TABLE_SIZE \
                         + HOST_TABLE_SIZE) * GATT_DB_STRUCT_SIZE)


/**
 * STRUCTURE DECLARATIONS
 ****************************************************************************************
 */

/**
 * GLOBAL VARIABLE DECLARATIONS
 ****************************************************************************************
 */

#endif /* _PRF_SEL_H_ */
