/*******************************************************************************
 * DISCLAIMER
 * This software is supplied by Renesas Electronics Corporation and is only
 * intended for use with Renesas products. No other uses are authorized. This
 * software is owned by Renesas Electronics Corporation and is protected under
 * all applicable laws, including copyright laws.
 * THIS SOFTWARE IS PROVIDED "AS IS" AND RENESAS MAKES NO WARRANTIES REGARDING
 * THIS SOFTWARE, WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING BUT NOT
 * LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE
 * AND NON-INFRINGEMENT. ALL SUCH WARRANTIES ARE EXPRESSLY DISCLAIMED.
 * TO THE MAXIMUM EXTENT PERMITTED NOT PROHIBITED BY LAW, NEITHER RENESAS
 * ELECTRONICS CORPORATION NOR ANY OF ITS AFFILIATED COMPANIES SHALL BE LIABLE
 * FOR ANY DIRECT, INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES FOR
 * ANY REASON RELATED TO THIS SOFTWARE, EVEN IF RENESAS OR ITS AFFILIATES HAVE
 * BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
 * Renesas reserves the right, without notice, to make changes to this software
 * and to discontinue the availability of this software. By using this software,
 * you agree to the additional terms and conditions found by accessing the
 * following link:
 * http://www.renesas.com/disclaimer
 * (C) 2012-2017 Renesas Electronics Corporation All rights reserved.
 ******************************************************************************/

/******************************************************************************
 * File Name  : rble_sample_app_peripheral.c
 * Version    : 1.0
 * Description: sample application peripheral role source file
 *
 * Copyright(C) 2013-2017 Renesas Electronics Corporation
 *
 * This file is generated by Bluetooth Developer Studio plugin.
 *     BDS Version    : 1.1.3139.0
 *     Script Version : 2.0.1
 *
 ******************************************************************************/

/*******************************************************************************
 * Include Files
 ******************************************************************************/
#include "rble_sample_app_peripheral.h"
#include "console.h"
#include "sam/sams.h"
#include "led_onoff.h"
#include "push_state.h"
#include "push_sw.h"

/*******************************************************************************
 * Macro Definitions
 ******************************************************************************/
#define APP_SWITCH_STATE_CHECK_INTERVAL (50)

/*******************************************************************************
 * Function Declarations
 ******************************************************************************/
static void app_msg_send(ke_msg_id_t id);
static int_t app_reset(ke_msg_id_t const msgid, void const *param,
                       ke_task_id_t const dest_id, ke_task_id_t const src_id);
static int_t app_advertise_start(ke_msg_id_t const msgid, void const *param,
                                 ke_task_id_t const dest_id, ke_task_id_t const src_id);
static int_t app_profile_enable(ke_msg_id_t const msgid, void const *param,
                                ke_task_id_t const dest_id, ke_task_id_t const src_id);
static int_t app_profile_disable(ke_msg_id_t const msgid, void const *param,
                                 ke_task_id_t const dest_id, ke_task_id_t const src_id);
static int_t app_timer_expired(ke_msg_id_t const msgid, void const *param,
                               ke_task_id_t const dest_id, ke_task_id_t const src_id);

static void app_gap_callback(RBLE_GAP_EVENT *event);
static void app_sams_callback(ENVIRONMENTAL_SENSING_SERVER_EVENT *event);

static void app_sm_callback(RBLE_SM_EVENT *event);

/*******************************************************************************
 * Global Variables
 ******************************************************************************/
static struct {
    uint16_t conhdl;
} app_info;

/* ##### Task Definitions ##### */
ke_state_t app_state[APP_IDX_MAX];

const struct ke_msg_handler app_reset_handler[] = {
    { APP_MSG_BOOTUP,        (ke_msg_func_t)app_reset },
};

const struct ke_msg_handler app_nonconnect_handler[] = {
    { APP_MSG_RESET_COMP,            (ke_msg_func_t)app_advertise_start },
    { APP_MSG_DISCONNECTED,          (ke_msg_func_t)app_profile_disable },
    { APP_MSG_PROFILE_DISABLED,      (ke_msg_func_t)app_advertise_start },
};

const struct ke_msg_handler app_connect_handler[] = {
    { APP_MSG_CONNECTED,       (ke_msg_func_t)app_profile_enable },
    /* { APP_MSG_PROFILE_ENABLED, (ke_msg_func_t)NULL }, */
    { APP_MSG_TIMER_EXPIRED,   (ke_msg_func_t)app_timer_expired },
};

const struct ke_state_handler app_state_handler[APP_STATE_MAX] =
{
    KE_STATE_HANDLER(app_reset_handler),
    KE_STATE_HANDLER(app_nonconnect_handler),
    KE_STATE_HANDLER(app_connect_handler),
};

/* ##### Advertise Parameter ##### */
static RBLE_ADV_INFO app_advertise_param = {
GAP SETTINGS : GAP setting is not done. Please set GAP SETTINGS. 
};

const struct ke_state_handler app_default_handler = KE_STATE_HANDLER_NONE;
ENVIRONMENTAL_SENSING_SERVER_PARAM samps_param = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };

/*******************************************************************************
 * Function Definitions (Internal)
 ******************************************************************************/
/* ##### Message Handler ##### */
static void app_msg_send(ke_msg_id_t id)
{
    /* Send blank msg to itself. The content is shared through
       app_info global variable. */
    ke_msg_send_basic(id, APP_TASK_ID, APP_TASK_ID);
}

static void sw2_pushed(void)
{
    uint8_t ntf_ind_val[20] = {0};

    if( samps_param.es_descriptor_value_changed_char_cccd & ENVIRONMENTAL_SENSING_SERVER_DESC_IND_ENABLE )
    {
        ntf_ind_val[0] = ENVIRONMENTAL_SENSING_HDL_ES_DESCRIPTOR_VALUE_CHANGED_VAL;
        (void)ENVIRONMENTAL_SENSING_Server_Char_NtfInd(app_info.conhdl, ENVIRONMENTAL_SENSING_HDL_ES_DESCRIPTOR_VALUE_CHANGED_VAL, (uint8_t *)&ntf_ind_val, ENVIRONMENTAL_SENSING_SERVER_DESC_IND_ENABLE);
    }
    if( samps_param.es_apparent_wind_direction_char_cccd & ENVIRONMENTAL_SENSING_SERVER_DESC_NTF_ENABLE )
    {
        ntf_ind_val[0] = ENVIRONMENTAL_SENSING_HDL_ES_APPARENT_WIND_DIRECTION_VAL;
        (void)ENVIRONMENTAL_SENSING_Server_Char_NtfInd(app_info.conhdl, ENVIRONMENTAL_SENSING_HDL_ES_APPARENT_WIND_DIRECTION_VAL, (uint8_t *)&ntf_ind_val, ENVIRONMENTAL_SENSING_SERVER_DESC_NTF_ENABLE);
    }
    if( samps_param.es_apparent_wind_speed_char_cccd & ENVIRONMENTAL_SENSING_SERVER_DESC_NTF_ENABLE )
    {
        ntf_ind_val[0] = ENVIRONMENTAL_SENSING_HDL_ES_APPARENT_WIND_SPEED_VAL;
        (void)ENVIRONMENTAL_SENSING_Server_Char_NtfInd(app_info.conhdl, ENVIRONMENTAL_SENSING_HDL_ES_APPARENT_WIND_SPEED_VAL, (uint8_t *)&ntf_ind_val, ENVIRONMENTAL_SENSING_SERVER_DESC_NTF_ENABLE);
    }
    if( samps_param.es_dew_point_char_cccd & ENVIRONMENTAL_SENSING_SERVER_DESC_NTF_ENABLE )
    {
        ntf_ind_val[0] = ENVIRONMENTAL_SENSING_HDL_ES_DEW_POINT_VAL;
        (void)ENVIRONMENTAL_SENSING_Server_Char_NtfInd(app_info.conhdl, ENVIRONMENTAL_SENSING_HDL_ES_DEW_POINT_VAL, (uint8_t *)&ntf_ind_val, ENVIRONMENTAL_SENSING_SERVER_DESC_NTF_ENABLE);
    }
    if( samps_param.es_elevation_char_cccd & ENVIRONMENTAL_SENSING_SERVER_DESC_NTF_ENABLE )
    {
        ntf_ind_val[0] = ENVIRONMENTAL_SENSING_HDL_ES_ELEVATION_VAL;
        (void)ENVIRONMENTAL_SENSING_Server_Char_NtfInd(app_info.conhdl, ENVIRONMENTAL_SENSING_HDL_ES_ELEVATION_VAL, (uint8_t *)&ntf_ind_val, ENVIRONMENTAL_SENSING_SERVER_DESC_NTF_ENABLE);
    }
    if( samps_param.es_gust_factor_char_cccd & ENVIRONMENTAL_SENSING_SERVER_DESC_NTF_ENABLE )
    {
        ntf_ind_val[0] = ENVIRONMENTAL_SENSING_HDL_ES_GUST_FACTOR_VAL;
        (void)ENVIRONMENTAL_SENSING_Server_Char_NtfInd(app_info.conhdl, ENVIRONMENTAL_SENSING_HDL_ES_GUST_FACTOR_VAL, (uint8_t *)&ntf_ind_val, ENVIRONMENTAL_SENSING_SERVER_DESC_NTF_ENABLE);
    }
    if( samps_param.es_heat_index_char_cccd & ENVIRONMENTAL_SENSING_SERVER_DESC_NTF_ENABLE )
    {
        ntf_ind_val[0] = ENVIRONMENTAL_SENSING_HDL_ES_HEAT_INDEX_VAL;
        (void)ENVIRONMENTAL_SENSING_Server_Char_NtfInd(app_info.conhdl, ENVIRONMENTAL_SENSING_HDL_ES_HEAT_INDEX_VAL, (uint8_t *)&ntf_ind_val, ENVIRONMENTAL_SENSING_SERVER_DESC_NTF_ENABLE);
    }
    if( samps_param.es_humidity_char_cccd & ENVIRONMENTAL_SENSING_SERVER_DESC_NTF_ENABLE )
    {
        ntf_ind_val[0] = ENVIRONMENTAL_SENSING_HDL_ES_HUMIDITY_VAL;
        (void)ENVIRONMENTAL_SENSING_Server_Char_NtfInd(app_info.conhdl, ENVIRONMENTAL_SENSING_HDL_ES_HUMIDITY_VAL, (uint8_t *)&ntf_ind_val, ENVIRONMENTAL_SENSING_SERVER_DESC_NTF_ENABLE);
    }
    if( samps_param.es_irradiance_char_cccd & ENVIRONMENTAL_SENSING_SERVER_DESC_NTF_ENABLE )
    {
        ntf_ind_val[0] = ENVIRONMENTAL_SENSING_HDL_ES_IRRADIANCE_VAL;
        (void)ENVIRONMENTAL_SENSING_Server_Char_NtfInd(app_info.conhdl, ENVIRONMENTAL_SENSING_HDL_ES_IRRADIANCE_VAL, (uint8_t *)&ntf_ind_val, ENVIRONMENTAL_SENSING_SERVER_DESC_NTF_ENABLE);
    }
    if( samps_param.es_pollen_concentration_char_cccd & ENVIRONMENTAL_SENSING_SERVER_DESC_NTF_ENABLE )
    {
        ntf_ind_val[0] = ENVIRONMENTAL_SENSING_HDL_ES_POLLEN_CONCENTRATION_VAL;
        (void)ENVIRONMENTAL_SENSING_Server_Char_NtfInd(app_info.conhdl, ENVIRONMENTAL_SENSING_HDL_ES_POLLEN_CONCENTRATION_VAL, (uint8_t *)&ntf_ind_val, ENVIRONMENTAL_SENSING_SERVER_DESC_NTF_ENABLE);
    }
    if( samps_param.es_rainfall_char_cccd & ENVIRONMENTAL_SENSING_SERVER_DESC_NTF_ENABLE )
    {
        ntf_ind_val[0] = ENVIRONMENTAL_SENSING_HDL_ES_RAINFALL_VAL;
        (void)ENVIRONMENTAL_SENSING_Server_Char_NtfInd(app_info.conhdl, ENVIRONMENTAL_SENSING_HDL_ES_RAINFALL_VAL, (uint8_t *)&ntf_ind_val, ENVIRONMENTAL_SENSING_SERVER_DESC_NTF_ENABLE);
    }
    if( samps_param.es_pressure_char_cccd & ENVIRONMENTAL_SENSING_SERVER_DESC_NTF_ENABLE )
    {
        ntf_ind_val[0] = ENVIRONMENTAL_SENSING_HDL_ES_PRESSURE_VAL;
        (void)ENVIRONMENTAL_SENSING_Server_Char_NtfInd(app_info.conhdl, ENVIRONMENTAL_SENSING_HDL_ES_PRESSURE_VAL, (uint8_t *)&ntf_ind_val, ENVIRONMENTAL_SENSING_SERVER_DESC_NTF_ENABLE);
    }
    if( samps_param.es_temperature_char_cccd & ENVIRONMENTAL_SENSING_SERVER_DESC_NTF_ENABLE )
    {
        ntf_ind_val[0] = ENVIRONMENTAL_SENSING_HDL_ES_TEMPERATURE_VAL;
        (void)ENVIRONMENTAL_SENSING_Server_Char_NtfInd(app_info.conhdl, ENVIRONMENTAL_SENSING_HDL_ES_TEMPERATURE_VAL, (uint8_t *)&ntf_ind_val, ENVIRONMENTAL_SENSING_SERVER_DESC_NTF_ENABLE);
    }
    if( samps_param.es_true_wind_direction_char_cccd & ENVIRONMENTAL_SENSING_SERVER_DESC_NTF_ENABLE )
    {
        ntf_ind_val[0] = ENVIRONMENTAL_SENSING_HDL_ES_TRUE_WIND_DIRECTION_VAL;
        (void)ENVIRONMENTAL_SENSING_Server_Char_NtfInd(app_info.conhdl, ENVIRONMENTAL_SENSING_HDL_ES_TRUE_WIND_DIRECTION_VAL, (uint8_t *)&ntf_ind_val, ENVIRONMENTAL_SENSING_SERVER_DESC_NTF_ENABLE);
    }
    if( samps_param.es_true_wind_speed_char_cccd & ENVIRONMENTAL_SENSING_SERVER_DESC_NTF_ENABLE )
    {
        ntf_ind_val[0] = ENVIRONMENTAL_SENSING_HDL_ES_TRUE_WIND_SPEED_VAL;
        (void)ENVIRONMENTAL_SENSING_Server_Char_NtfInd(app_info.conhdl, ENVIRONMENTAL_SENSING_HDL_ES_TRUE_WIND_SPEED_VAL, (uint8_t *)&ntf_ind_val, ENVIRONMENTAL_SENSING_SERVER_DESC_NTF_ENABLE);
    }
    if( samps_param.es_uv_index_char_cccd & ENVIRONMENTAL_SENSING_SERVER_DESC_NTF_ENABLE )
    {
        ntf_ind_val[0] = ENVIRONMENTAL_SENSING_HDL_ES_UV_INDEX_VAL;
        (void)ENVIRONMENTAL_SENSING_Server_Char_NtfInd(app_info.conhdl, ENVIRONMENTAL_SENSING_HDL_ES_UV_INDEX_VAL, (uint8_t *)&ntf_ind_val, ENVIRONMENTAL_SENSING_SERVER_DESC_NTF_ENABLE);
    }
    if( samps_param.es_wind_chill_char_cccd & ENVIRONMENTAL_SENSING_SERVER_DESC_NTF_ENABLE )
    {
        ntf_ind_val[0] = ENVIRONMENTAL_SENSING_HDL_ES_WIND_CHILL_VAL;
        (void)ENVIRONMENTAL_SENSING_Server_Char_NtfInd(app_info.conhdl, ENVIRONMENTAL_SENSING_HDL_ES_WIND_CHILL_VAL, (uint8_t *)&ntf_ind_val, ENVIRONMENTAL_SENSING_SERVER_DESC_NTF_ENABLE);
    }
    if( samps_param.es_barometric_pressure_trend_char_cccd & ENVIRONMENTAL_SENSING_SERVER_DESC_NTF_ENABLE )
    {
        ntf_ind_val[0] = ENVIRONMENTAL_SENSING_HDL_ES_BAROMETRIC_PRESSURE_TREND_VAL;
        (void)ENVIRONMENTAL_SENSING_Server_Char_NtfInd(app_info.conhdl, ENVIRONMENTAL_SENSING_HDL_ES_BAROMETRIC_PRESSURE_TREND_VAL, (uint8_t *)&ntf_ind_val, ENVIRONMENTAL_SENSING_SERVER_DESC_NTF_ENABLE);
    }
    if( samps_param.es_magnetic_declination_char_cccd & ENVIRONMENTAL_SENSING_SERVER_DESC_NTF_ENABLE )
    {
        ntf_ind_val[0] = ENVIRONMENTAL_SENSING_HDL_ES_MAGNETIC_DECLINATION_VAL;
        (void)ENVIRONMENTAL_SENSING_Server_Char_NtfInd(app_info.conhdl, ENVIRONMENTAL_SENSING_HDL_ES_MAGNETIC_DECLINATION_VAL, (uint8_t *)&ntf_ind_val, ENVIRONMENTAL_SENSING_SERVER_DESC_NTF_ENABLE);
    }
    if( samps_param.es_magnetic_flux_density___2d_char_cccd & ENVIRONMENTAL_SENSING_SERVER_DESC_NTF_ENABLE )
    {
        ntf_ind_val[0] = ENVIRONMENTAL_SENSING_HDL_ES_MAGNETIC_FLUX_DENSITY___2D_VAL;
        (void)ENVIRONMENTAL_SENSING_Server_Char_NtfInd(app_info.conhdl, ENVIRONMENTAL_SENSING_HDL_ES_MAGNETIC_FLUX_DENSITY___2D_VAL, (uint8_t *)&ntf_ind_val, ENVIRONMENTAL_SENSING_SERVER_DESC_NTF_ENABLE);
    }
    if( samps_param.es_magnetic_flux_density___3d_char_cccd & ENVIRONMENTAL_SENSING_SERVER_DESC_NTF_ENABLE )
    {
        ntf_ind_val[0] = ENVIRONMENTAL_SENSING_HDL_ES_MAGNETIC_FLUX_DENSITY___3D_VAL;
        (void)ENVIRONMENTAL_SENSING_Server_Char_NtfInd(app_info.conhdl, ENVIRONMENTAL_SENSING_HDL_ES_MAGNETIC_FLUX_DENSITY___3D_VAL, (uint8_t *)&ntf_ind_val, ENVIRONMENTAL_SENSING_SERVER_DESC_NTF_ENABLE);
    }
    if( samps_param.bs_battery_level_char_cccd & ENVIRONMENTAL_SENSING_SERVER_DESC_NTF_ENABLE )
    {
        ntf_ind_val[0] = ENVIRONMENTAL_SENSING_HDL_BS_BATTERY_LEVEL_VAL;
        (void)ENVIRONMENTAL_SENSING_Server_Char_NtfInd(app_info.conhdl, ENVIRONMENTAL_SENSING_HDL_BS_BATTERY_LEVEL_VAL, (uint8_t *)&ntf_ind_val, ENVIRONMENTAL_SENSING_SERVER_DESC_NTF_ENABLE);
    }
}

static int_t app_reset(ke_msg_id_t const msgid, void const *param,
                       ke_task_id_t const dest_id, ke_task_id_t const src_id)
{
    (void)led_onoff_init(R_LED4);
    (void)push_state_init(R_SW4);
    (void)push_sw2_start(sw2_pushed);

    (void)RBLE_GAP_Reset(&app_gap_callback, &app_sm_callback);

    return KE_MSG_CONSUMED;
}

static int_t app_advertise_start(ke_msg_id_t const msgid, void const *param,
                                 ke_task_id_t const dest_id, ke_task_id_t const src_id)
{
    (void)RBLE_GAP_Broadcast_Enable(
        RBLE_GAP_GEN_DISCOVERABLE, RBLE_GAP_UND_CONNECTABLE,
        &app_advertise_param);

    return KE_MSG_CONSUMED;
}

static int_t app_profile_enable(ke_msg_id_t const msgid, void const *param,
                                ke_task_id_t const dest_id, ke_task_id_t const src_id)
{
    (void)ENVIRONMENTAL_SENSING_Server_Enable(app_info.conhdl, RBLE_PRF_CON_DISCOVERY,
                               &samps_param, &app_sams_callback);

    return KE_MSG_CONSUMED;
}

static int_t app_profile_disable(ke_msg_id_t const msgid, void const *param,
                                 ke_task_id_t const dest_id, ke_task_id_t const src_id)
{
    (void)ENVIRONMENTAL_SENSING_Server_Disable(app_info.conhdl);

    return KE_MSG_CONSUMED;
}

static int_t app_timer_expired(ke_msg_id_t const msgid, void const *param,
                               ke_task_id_t const dest_id, ke_task_id_t const src_id)
{

    return KE_MSG_CONSUMED;
}

/* ##### GAP Event Handler ##### */
void app_gap_callback(RBLE_GAP_EVENT *event)
{
    switch (event->type) {
    case RBLE_GAP_EVENT_RESET_RESULT:
        ke_state_set(APP_TASK_ID, APP_NONCONNECT_STATE);
        app_msg_send(APP_MSG_RESET_COMP);
        break;

    case RBLE_GAP_EVENT_BROADCAST_ENABLE_COMP:
    case RBLE_GAP_EVENT_BROADCAST_DISABLE_COMP:
        /* do nothing */
        break;

    case RBLE_GAP_EVENT_CONNECTION_COMP:
        if (RBLE_OK == event->param.status) {
            app_info.conhdl = event->param.conn_comp.connect_info.conhdl;
            ke_state_set(APP_TASK_ID, APP_CONNECT_STATE);
            app_msg_send(APP_MSG_CONNECTED);
        } else {
            ke_state_set(APP_TASK_ID, APP_NONCONNECT_STATE);
            app_msg_send(APP_MSG_DISCONNECTED);
        }
        break;

    case RBLE_GAP_EVENT_DISCONNECT_COMP:
        ke_state_set(APP_TASK_ID, APP_NONCONNECT_STATE);
        app_msg_send(APP_MSG_DISCONNECTED);
        break;

    default:
        Printf("unsupported GAP event: 0x%x\n", event->type);
        break;
    }
}

/* ##### SM Event Handler ##### */
void app_sm_callback(RBLE_SM_EVENT *event)
{
    Printf("unsupported event: 0x%x\n", event->type);
}

/* ##### Sample Custom Profile Handler ##### */
void app_sams_callback(ENVIRONMENTAL_SENSING_SERVER_EVENT *event)
{
    switch (event->type) {
    case ENVIRONMENTAL_SENSING_SERVER_EVENT_ENABLE_COMP:
        app_msg_send(APP_MSG_PROFILE_ENABLED);
        break;

    case ENVIRONMENTAL_SENSING_SERVER_EVENT_DISABLE_COMP:
        app_msg_send(APP_MSG_PROFILE_DISABLED);
        break;

    case ENVIRONMENTAL_SENSING_SERVER_EVENT_CCCD_WRITE:
        switch(event->param.cccd_write_evt.char_hdl) {
        case ENVIRONMENTAL_SENSING_HDL_ES_DESCRIPTOR_VALUE_CHANGED_CCCD:
            samps_param.es_descriptor_value_changed_char_cccd = event->param.cccd_write_evt.value;
            break;
            
        case ENVIRONMENTAL_SENSING_HDL_ES_APPARENT_WIND_DIRECTION_CCCD:
            samps_param.es_apparent_wind_direction_char_cccd = event->param.cccd_write_evt.value;
            break;
            
        case ENVIRONMENTAL_SENSING_HDL_ES_APPARENT_WIND_SPEED_CCCD:
            samps_param.es_apparent_wind_speed_char_cccd = event->param.cccd_write_evt.value;
            break;
            
        case ENVIRONMENTAL_SENSING_HDL_ES_DEW_POINT_CCCD:
            samps_param.es_dew_point_char_cccd = event->param.cccd_write_evt.value;
            break;
            
        case ENVIRONMENTAL_SENSING_HDL_ES_ELEVATION_CCCD:
            samps_param.es_elevation_char_cccd = event->param.cccd_write_evt.value;
            break;
            
        case ENVIRONMENTAL_SENSING_HDL_ES_GUST_FACTOR_CCCD:
            samps_param.es_gust_factor_char_cccd = event->param.cccd_write_evt.value;
            break;
            
        case ENVIRONMENTAL_SENSING_HDL_ES_HEAT_INDEX_CCCD:
            samps_param.es_heat_index_char_cccd = event->param.cccd_write_evt.value;
            break;
            
        case ENVIRONMENTAL_SENSING_HDL_ES_HUMIDITY_CCCD:
            samps_param.es_humidity_char_cccd = event->param.cccd_write_evt.value;
            break;
            
        case ENVIRONMENTAL_SENSING_HDL_ES_IRRADIANCE_CCCD:
            samps_param.es_irradiance_char_cccd = event->param.cccd_write_evt.value;
            break;
            
        case ENVIRONMENTAL_SENSING_HDL_ES_POLLEN_CONCENTRATION_CCCD:
            samps_param.es_pollen_concentration_char_cccd = event->param.cccd_write_evt.value;
            break;
            
        case ENVIRONMENTAL_SENSING_HDL_ES_RAINFALL_CCCD:
            samps_param.es_rainfall_char_cccd = event->param.cccd_write_evt.value;
            break;
            
        case ENVIRONMENTAL_SENSING_HDL_ES_PRESSURE_CCCD:
            samps_param.es_pressure_char_cccd = event->param.cccd_write_evt.value;
            break;
            
        case ENVIRONMENTAL_SENSING_HDL_ES_TEMPERATURE_CCCD:
            samps_param.es_temperature_char_cccd = event->param.cccd_write_evt.value;
            break;
            
        case ENVIRONMENTAL_SENSING_HDL_ES_TRUE_WIND_DIRECTION_CCCD:
            samps_param.es_true_wind_direction_char_cccd = event->param.cccd_write_evt.value;
            break;
            
        case ENVIRONMENTAL_SENSING_HDL_ES_TRUE_WIND_SPEED_CCCD:
            samps_param.es_true_wind_speed_char_cccd = event->param.cccd_write_evt.value;
            break;
            
        case ENVIRONMENTAL_SENSING_HDL_ES_UV_INDEX_CCCD:
            samps_param.es_uv_index_char_cccd = event->param.cccd_write_evt.value;
            break;
            
        case ENVIRONMENTAL_SENSING_HDL_ES_WIND_CHILL_CCCD:
            samps_param.es_wind_chill_char_cccd = event->param.cccd_write_evt.value;
            break;
            
        case ENVIRONMENTAL_SENSING_HDL_ES_BAROMETRIC_PRESSURE_TREND_CCCD:
            samps_param.es_barometric_pressure_trend_char_cccd = event->param.cccd_write_evt.value;
            break;
            
        case ENVIRONMENTAL_SENSING_HDL_ES_MAGNETIC_DECLINATION_CCCD:
            samps_param.es_magnetic_declination_char_cccd = event->param.cccd_write_evt.value;
            break;
            
        case ENVIRONMENTAL_SENSING_HDL_ES_MAGNETIC_FLUX_DENSITY___2D_CCCD:
            samps_param.es_magnetic_flux_density___2d_char_cccd = event->param.cccd_write_evt.value;
            break;
            
        case ENVIRONMENTAL_SENSING_HDL_ES_MAGNETIC_FLUX_DENSITY___3D_CCCD:
            samps_param.es_magnetic_flux_density___3d_char_cccd = event->param.cccd_write_evt.value;
            break;
            
        case ENVIRONMENTAL_SENSING_HDL_BS_BATTERY_LEVEL_CCCD:
            samps_param.bs_battery_level_char_cccd = event->param.cccd_write_evt.value;
            break;
            
        default:
            Printf("unsupported hdl: 0x%x\n", event->param.cccd_write_evt.char_hdl);
            break;
        }
        break;

    case ENVIRONMENTAL_SENSING_SERVER_EVENT_NOTIFY_COMP:
        break;

    case ENVIRONMENTAL_SENSING_SERVER_EVENT_INDICATE_COMP:
        break;

    default:
        Printf("unsupported SAMS event: 0x%x\n", event->type);
        break;
    }
}

/* ##### Application Handler ##### */
void app_callback(RBLE_MODE mode)
{
    switch (mode) {
    case RBLE_MODE_ACTIVE:
        app_msg_send(APP_MSG_BOOTUP);
        break;

    case RBLE_MODE_INITIALIZE:
    case RBLE_MODE_RESET:
    case RBLE_MODE_SLEEP:
    case RBLE_MODE_ERROR:
        /* do nothing */
        break;

    default:
        Printf("unknown mode: 0x%x\n", mode);
        break;
    }
}

BOOL RBLE_App_Init(void)
{
    RBLE_STATUS status;

    status = RBLE_Init(&app_callback);
    if (RBLE_OK != status) {
        return FALSE;
    }

    ke_state_set(APP_TASK_ID, APP_RESET_STATE);

    console_init(false, 0);

    return TRUE;
}
