/**
 ****************************************************************************************
 *
 * @file    sam.h
 *
 * Copyright(C) 2013-2017 Renesas Electronics Corporation
 *
 * This file is generated by Bluetooth Developer Studio plugin.
 *     BDS Version    : 1.1.3139.0
 *     Script Version : 2.0.1
 *
 ****************************************************************************************
 */
#ifndef __SAM_H__
#define __SAM_H__

#define RBLE_BDS_SVC_ENVIRONMENTAL_SENSING                                {0x1A,0x18}	/* Service: Environmental Sensing */
#define RBLE_BDS_CHAR_ES_DESCRIPTOR_VALUE_CHANGED                            {0x7D,0x2A}	/* Characteristic: Descriptor Value Changed */
#define RBLE_BDS_CHAR_ES_APPARENT_WIND_DIRECTION                             {0x73,0x2A}	/* Characteristic: Apparent Wind Direction */
#define RBLE_BDS_CHAR_ES_APPARENT_WIND_SPEED                                 {0x72,0x2A}	/* Characteristic: Apparent Wind Speed */
#define RBLE_BDS_CHAR_ES_DEW_POINT                                           {0x7B,0x2A}	/* Characteristic: Dew Point */
#define RBLE_BDS_CHAR_ES_ELEVATION                                           {0x6C,0x2A}	/* Characteristic: Elevation */
#define RBLE_BDS_CHAR_ES_GUST_FACTOR                                         {0x74,0x2A}	/* Characteristic: Gust Factor */
#define RBLE_BDS_CHAR_ES_HEAT_INDEX                                          {0x7A,0x2A}	/* Characteristic: Heat Index */
#define RBLE_BDS_CHAR_ES_HUMIDITY                                            {0x6F,0x2A}	/* Characteristic: Humidity */
#define RBLE_BDS_CHAR_ES_IRRADIANCE                                          {0x77,0x2A}	/* Characteristic: Irradiance */
#define RBLE_BDS_CHAR_ES_POLLEN_CONCENTRATION                                {0x75,0x2A}	/* Characteristic: Pollen Concentration */
#define RBLE_BDS_CHAR_ES_RAINFALL                                            {0x78,0x2A}	/* Characteristic: Rainfall */
#define RBLE_BDS_CHAR_ES_PRESSURE                                            {0x6D,0x2A}	/* Characteristic: Pressure */
#define RBLE_BDS_CHAR_ES_TEMPERATURE                                         {0x6E,0x2A}	/* Characteristic: Temperature */
#define RBLE_BDS_CHAR_ES_TRUE_WIND_DIRECTION                                 {0x71,0x2A}	/* Characteristic: True Wind Direction */
#define RBLE_BDS_CHAR_ES_TRUE_WIND_SPEED                                     {0x70,0x2A}	/* Characteristic: True Wind Speed */
#define RBLE_BDS_CHAR_ES_UV_INDEX                                            {0x76,0x2A}	/* Characteristic: UV Index */
#define RBLE_BDS_CHAR_ES_WIND_CHILL                                          {0x79,0x2A}	/* Characteristic: Wind Chill */
#define RBLE_BDS_CHAR_ES_BAROMETRIC_PRESSURE_TREND                           {0xA3,0x2A}	/* Characteristic: Barometric Pressure Trend */
#define RBLE_BDS_CHAR_ES_MAGNETIC_DECLINATION                                {0x2C,0x2A}	/* Characteristic: Magnetic Declination */
#define RBLE_BDS_CHAR_ES_MAGNETIC_FLUX_DENSITY___2D                          {0xA0,0x2A}	/* Characteristic: Magnetic Flux Density - 2D */
#define RBLE_BDS_CHAR_ES_MAGNETIC_FLUX_DENSITY___3D                          {0xA1,0x2A}	/* Characteristic: Magnetic Flux Density - 3D */

#define RBLE_BDS_SVC_DEVICE_INFORMATION                                   {0x0A,0x18}	/* Service: Device Information */
#define RBLE_BDS_CHAR_DI_MANUFACTURER_NAME_STRING                            {0x29,0x2A}	/* Characteristic: Manufacturer Name String */
#define RBLE_BDS_CHAR_DI_MODEL_NUMBER_STRING                                 {0x24,0x2A}	/* Characteristic: Model Number String */
#define RBLE_BDS_CHAR_DI_SERIAL_NUMBER_STRING                                {0x25,0x2A}	/* Characteristic: Serial Number String */
#define RBLE_BDS_CHAR_DI_HARDWARE_REVISION_STRING                            {0x27,0x2A}	/* Characteristic: Hardware Revision String */
#define RBLE_BDS_CHAR_DI_FIRMWARE_REVISION_STRING                            {0x26,0x2A}	/* Characteristic: Firmware Revision String */
#define RBLE_BDS_CHAR_DI_SOFTWARE_REVISION_STRING                            {0x28,0x2A}	/* Characteristic: Software Revision String */
#define RBLE_BDS_CHAR_DI_SYSTEM_ID                                           {0x23,0x2A}	/* Characteristic: System ID */
#define RBLE_BDS_CHAR_DI_IEEE_11073_20601_REGULATORY_CERTIFICATION_DATA_LIST {0x2A,0x2A}	/* Characteristic: IEEE 11073-20601 Regulatory Certification Data List */
#define RBLE_BDS_CHAR_DI_PNP_ID                                              {0x50,0x2A}	/* Characteristic: PnP ID */

#define RBLE_BDS_SVC_BATTERY_SERVICE                                      {0x0F,0x18}	/* Service: Battery Service */
#define RBLE_BDS_CHAR_BS_BATTERY_LEVEL                                       {0x19,0x2A}	/* Characteristic: Battery Level */


#define ENVIRONMENTAL_SENSING_SERVER_CCCD_SIZE         (2)

enum RBLE_ATT_ERR_CUSTOM_CODE_enum {
    RBLE_ATT_ERR_QUEUE_FULL = 0x81,     /* Set_Data queue is full */
};

#endif /* __SAM_H__ */
