/*******************************************************************************
 * DISCLAIMER
 * This software is supplied by Renesas Electronics Corporation and is only
 * intended for use with Renesas products. No other uses are authorized. This
 * software is owned by Renesas Electronics Corporation and is protected under
 * all applicable laws, including copyright laws.
 * THIS SOFTWARE IS PROVIDED "AS IS" AND RENESAS MAKES NO WARRANTIES REGARDING
 * THIS SOFTWARE, WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING BUT NOT
 * LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE
 * AND NON-INFRINGEMENT. ALL SUCH WARRANTIES ARE EXPRESSLY DISCLAIMED.
 * TO THE MAXIMUM EXTENT PERMITTED NOT PROHIBITED BY LAW, NEITHER RENESAS
 * ELECTRONICS CORPORATION NOR ANY OF ITS AFFILIATED COMPANIES SHALL BE LIABLE
 * FOR ANY DIRECT, INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES FOR
 * ANY REASON RELATED TO THIS SOFTWARE, EVEN IF RENESAS OR ITS AFFILIATES HAVE
 * BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
 * Renesas reserves the right, without notice, to make changes to this software
 * and to discontinue the availability of this software. By using this software,
 * you agree to the additional terms and conditions found by accessing the
 * following link:
 * http://www.renesas.com/disclaimer
 * (C) 2012-2017 Renesas Electronics Corporation All rights reserved.
 ******************************************************************************/

/******************************************************************************
 * File Name  : sams.c
 * Version    : 1.0
 * Description: sample custom profile server role code file
 *
 * Copyright(C) 2013-2017 Renesas Electronics Corporation
 *
 * This file is generated by Bluetooth Developer Studio plugin.
 *     BDS Version    : 1.1.3139.0
 *     Script Version : 2.0.1
 *
 ******************************************************************************/

/*******************************************************************************
 * Include Files
 ******************************************************************************/
#include <string.h>

#include "sams.h"
#include "rble_api.h"
#include "db_handle.h"

/*******************************************************************************
 * Enumeration Definitions
 ******************************************************************************/
typedef enum {
    ENVIRONMENTAL_SENSING_SERVER_STATE_IDLE,
    ENVIRONMENTAL_SENSING_SERVER_STATE_INIT,
    ENVIRONMENTAL_SENSING_SERVER_STATE_CONNECTED,
} ENVIRONMENTAL_SENSING_SERVER_STATE;

typedef enum {
	ENVIRONMENTAL_SENSING_SERVER_INIT_STATE_ES__DESCRIPTOR_VALUE_CHANGED_CCCD,
	ENVIRONMENTAL_SENSING_SERVER_INIT_STATE_ES__APPARENT_WIND_DIRECTION_CCCD,
	ENVIRONMENTAL_SENSING_SERVER_INIT_STATE_ES__APPARENT_WIND_SPEED_CCCD,
	ENVIRONMENTAL_SENSING_SERVER_INIT_STATE_ES__DEW_POINT_CCCD,
	ENVIRONMENTAL_SENSING_SERVER_INIT_STATE_ES__ELEVATION_CCCD,
	ENVIRONMENTAL_SENSING_SERVER_INIT_STATE_ES__GUST_FACTOR_CCCD,
	ENVIRONMENTAL_SENSING_SERVER_INIT_STATE_ES__HEAT_INDEX_CCCD,
	ENVIRONMENTAL_SENSING_SERVER_INIT_STATE_ES__HUMIDITY_CCCD,
	ENVIRONMENTAL_SENSING_SERVER_INIT_STATE_ES__IRRADIANCE_CCCD,
	ENVIRONMENTAL_SENSING_SERVER_INIT_STATE_ES__POLLEN_CONCENTRATION_CCCD,
	ENVIRONMENTAL_SENSING_SERVER_INIT_STATE_ES__RAINFALL_CCCD,
	ENVIRONMENTAL_SENSING_SERVER_INIT_STATE_ES__PRESSURE_CCCD,
	ENVIRONMENTAL_SENSING_SERVER_INIT_STATE_ES__TEMPERATURE_CCCD,
	ENVIRONMENTAL_SENSING_SERVER_INIT_STATE_ES__TRUE_WIND_DIRECTION_CCCD,
	ENVIRONMENTAL_SENSING_SERVER_INIT_STATE_ES__TRUE_WIND_SPEED_CCCD,
	ENVIRONMENTAL_SENSING_SERVER_INIT_STATE_ES__UV_INDEX_CCCD,
	ENVIRONMENTAL_SENSING_SERVER_INIT_STATE_ES__WIND_CHILL_CCCD,
	ENVIRONMENTAL_SENSING_SERVER_INIT_STATE_ES__BAROMETRIC_PRESSURE_TREND_CCCD,
	ENVIRONMENTAL_SENSING_SERVER_INIT_STATE_ES__MAGNETIC_DECLINATION_CCCD,
	ENVIRONMENTAL_SENSING_SERVER_INIT_STATE_ES__MAGNETIC_FLUX_DENSITY___2D_CCCD,
	ENVIRONMENTAL_SENSING_SERVER_INIT_STATE_ES__MAGNETIC_FLUX_DENSITY___3D_CCCD,
	ENVIRONMENTAL_SENSING_SERVER_INIT_STATE_BS__BATTERY_LEVEL_CCCD,
    ENVIRONMENTAL_SENSING_SERVER_INIT_STATE_END,
} ENVIRONMENTAL_SENSING_SERVER_INIT_STATE;

/*******************************************************************************
 * Global Variables
 ******************************************************************************/
static struct {
    uint16_t conhdl;
    ENVIRONMENTAL_SENSING_SERVER_STATE state;
    ENVIRONMENTAL_SENSING_SERVER_INIT_STATE init_state;
    ENVIRONMENTAL_SENSING_SERVER_PARAM param;
    ENVIRONMENTAL_SENSING_SERVER_EVENT_HANDLER callback;
    RBLE_STATUS status;
    /* for set_data & write_cmd handling */
    uint16_t hdl;
    uint16_t len;
    uint8_t  value[20];
    uint16_t send_ntf_ind;
    BOOL     write_cmd_ind;
} info;

typedef struct {
    uint16_t hdl;
    uint16_t len;
    uint8_t  value[20];
    uint16_t send_ntf_ind;
    BOOL     write_cmd_ind;
} SET_DATA_INFO;

#define QUEUE_MAX 3
static SET_DATA_INFO queue[QUEUE_MAX];

static uint8_t queue_ct = 0;   /* Number of queueing [0 - (QUEUE_MAX -1)] */
static uint8_t queue_w_p = 0;  /* Queueing write pointer */ 
static uint8_t queue_r_p = 0;  /* Queueing read pointer */

static BOOL now_set_data = FALSE;


/*******************************************************************************
 * Function Declarations
 ******************************************************************************/
static void environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_TYPE type);
static void environmental_sensing_server_set_cccd(uint16_t cccd_hdl, uint16_t cccd_val);

static void environmental_sensing_server_set_init_data(void);
static void environmental_sensing_server_set_data(SET_DATA_INFO *sd_info);
static void environmental_sensing_server_notify_request(uint16_t conhdl, uint16_t charhdl);
static void environmental_sensing_server_indicate_request(uint16_t conhdl, uint16_t charhdl);
static void environmental_sensing_server_write_resp(BOOL flg);
static void environmental_sensing_server_set_data_cmp_handler(RBLE_GATT_EVENT *event);
static void environmental_sensing_server_write_cmd_ind_handler(RBLE_GATT_EVENT *event);
static void environmental_sensing_server_handle_value_cfm_handler(RBLE_GATT_EVENT *event);
static void environmental_sensing_server_notify_comp_handler(RBLE_GATT_EVENT *event);
static void environmental_sensing_server_gatt_callback(RBLE_GATT_EVENT *event);
static BOOL environmental_sensing_server_set_data_queueing(SET_DATA_INFO *data);
static BOOL environmental_sensing_server_set_data_queue_read(SET_DATA_INFO *data);

/*******************************************************************************
 * Function Definitions (Internal)
 ******************************************************************************/
static void environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_TYPE type)
{
    ENVIRONMENTAL_SENSING_SERVER_EVENT event;

    event.type   = type;
    event.conhdl = info.conhdl;

    switch (type) {
    case ENVIRONMENTAL_SENSING_SERVER_EVENT_ENABLE_COMP:
        event.status = info.status;
        break;

    case ENVIRONMENTAL_SENSING_SERVER_EVENT_DISABLE_COMP:
		event.param.disable_comp_evt.param.es_descriptor_value_changed_char_cccd = info.param.es_descriptor_value_changed_char_cccd;
		event.param.disable_comp_evt.param.es_apparent_wind_direction_char_cccd = info.param.es_apparent_wind_direction_char_cccd;
		event.param.disable_comp_evt.param.es_apparent_wind_speed_char_cccd = info.param.es_apparent_wind_speed_char_cccd;
		event.param.disable_comp_evt.param.es_dew_point_char_cccd = info.param.es_dew_point_char_cccd;
		event.param.disable_comp_evt.param.es_elevation_char_cccd = info.param.es_elevation_char_cccd;
		event.param.disable_comp_evt.param.es_gust_factor_char_cccd = info.param.es_gust_factor_char_cccd;
		event.param.disable_comp_evt.param.es_heat_index_char_cccd = info.param.es_heat_index_char_cccd;
		event.param.disable_comp_evt.param.es_humidity_char_cccd = info.param.es_humidity_char_cccd;
		event.param.disable_comp_evt.param.es_irradiance_char_cccd = info.param.es_irradiance_char_cccd;
		event.param.disable_comp_evt.param.es_pollen_concentration_char_cccd = info.param.es_pollen_concentration_char_cccd;
		event.param.disable_comp_evt.param.es_rainfall_char_cccd = info.param.es_rainfall_char_cccd;
		event.param.disable_comp_evt.param.es_pressure_char_cccd = info.param.es_pressure_char_cccd;
		event.param.disable_comp_evt.param.es_temperature_char_cccd = info.param.es_temperature_char_cccd;
		event.param.disable_comp_evt.param.es_true_wind_direction_char_cccd = info.param.es_true_wind_direction_char_cccd;
		event.param.disable_comp_evt.param.es_true_wind_speed_char_cccd = info.param.es_true_wind_speed_char_cccd;
		event.param.disable_comp_evt.param.es_uv_index_char_cccd = info.param.es_uv_index_char_cccd;
		event.param.disable_comp_evt.param.es_wind_chill_char_cccd = info.param.es_wind_chill_char_cccd;
		event.param.disable_comp_evt.param.es_barometric_pressure_trend_char_cccd = info.param.es_barometric_pressure_trend_char_cccd;
		event.param.disable_comp_evt.param.es_magnetic_declination_char_cccd = info.param.es_magnetic_declination_char_cccd;
		event.param.disable_comp_evt.param.es_magnetic_flux_density___2d_char_cccd = info.param.es_magnetic_flux_density___2d_char_cccd;
		event.param.disable_comp_evt.param.es_magnetic_flux_density___3d_char_cccd = info.param.es_magnetic_flux_density___3d_char_cccd;
		event.param.disable_comp_evt.param.bs_battery_level_char_cccd = info.param.bs_battery_level_char_cccd;
        event.status = info.status;
        break;
        
    case ENVIRONMENTAL_SENSING_SERVER_EVENT_CCCD_WRITE:
        event.status = info.status;
        event.param.cccd_write_evt.char_hdl = info.hdl;
        event.param.cccd_write_evt.value    = (uint16_t)((info.value[1] << 8) | info.value[0]);
        break;
        
    case ENVIRONMENTAL_SENSING_SERVER_EVENT_NOTIFY_COMP:
        event.status = info.status;
        event.param.ntf_comp_evt.char_hdl = info.hdl;
        break;
        
    case ENVIRONMENTAL_SENSING_SERVER_EVENT_INDICATE_COMP:
        event.status = info.status;
        event.param.ind_comp_evt.char_hdl = info.hdl;
        break;
        
    case ENVIRONMENTAL_SENSING_SERVER_EVENT_SET_VALUE_COMP:
        event.status = info.status;
        event.param.set_value_comp_evt.char_hdl = info.hdl;
        break;
        
    default:
        /* Unsupported ENVIRONMENTAL_SENSING_SERVER event */
        break;
    }

    info.callback(&event);
}

static void environmental_sensing_server_set_cccd(uint16_t cccd_hdl, uint16_t cccd_val)
{
    SET_DATA_INFO data;
    
    data.hdl = cccd_hdl;
    data.len = ENVIRONMENTAL_SENSING_SERVER_CCCD_SIZE;
    memcpy(data.value, &cccd_val, data.len);
    data.send_ntf_ind = ENVIRONMENTAL_SENSING_SERVER_DESC_ALL_DISABLE;
    data.write_cmd_ind = FALSE;
    environmental_sensing_server_set_data_queueing(&data);
}

static void environmental_sensing_server_set_init_data(void)
{
    switch (info.init_state) {

    case ENVIRONMENTAL_SENSING_SERVER_INIT_STATE_ES__DESCRIPTOR_VALUE_CHANGED_CCCD:
        environmental_sensing_server_set_cccd(ENVIRONMENTAL_SENSING_HDL_ES_DESCRIPTOR_VALUE_CHANGED_CCCD, info.param.es_descriptor_value_changed_char_cccd);
        info.init_state++;
        break;
        
    case ENVIRONMENTAL_SENSING_SERVER_INIT_STATE_ES__APPARENT_WIND_DIRECTION_CCCD:
        environmental_sensing_server_set_cccd(ENVIRONMENTAL_SENSING_HDL_ES_APPARENT_WIND_DIRECTION_CCCD, info.param.es_apparent_wind_direction_char_cccd);
        info.init_state++;
        break;
        
    case ENVIRONMENTAL_SENSING_SERVER_INIT_STATE_ES__APPARENT_WIND_SPEED_CCCD:
        environmental_sensing_server_set_cccd(ENVIRONMENTAL_SENSING_HDL_ES_APPARENT_WIND_SPEED_CCCD, info.param.es_apparent_wind_speed_char_cccd);
        info.init_state++;
        break;
        
    case ENVIRONMENTAL_SENSING_SERVER_INIT_STATE_ES__DEW_POINT_CCCD:
        environmental_sensing_server_set_cccd(ENVIRONMENTAL_SENSING_HDL_ES_DEW_POINT_CCCD, info.param.es_dew_point_char_cccd);
        info.init_state++;
        break;
        
    case ENVIRONMENTAL_SENSING_SERVER_INIT_STATE_ES__ELEVATION_CCCD:
        environmental_sensing_server_set_cccd(ENVIRONMENTAL_SENSING_HDL_ES_ELEVATION_CCCD, info.param.es_elevation_char_cccd);
        info.init_state++;
        break;
        
    case ENVIRONMENTAL_SENSING_SERVER_INIT_STATE_ES__GUST_FACTOR_CCCD:
        environmental_sensing_server_set_cccd(ENVIRONMENTAL_SENSING_HDL_ES_GUST_FACTOR_CCCD, info.param.es_gust_factor_char_cccd);
        info.init_state++;
        break;
        
    case ENVIRONMENTAL_SENSING_SERVER_INIT_STATE_ES__HEAT_INDEX_CCCD:
        environmental_sensing_server_set_cccd(ENVIRONMENTAL_SENSING_HDL_ES_HEAT_INDEX_CCCD, info.param.es_heat_index_char_cccd);
        info.init_state++;
        break;
        
    case ENVIRONMENTAL_SENSING_SERVER_INIT_STATE_ES__HUMIDITY_CCCD:
        environmental_sensing_server_set_cccd(ENVIRONMENTAL_SENSING_HDL_ES_HUMIDITY_CCCD, info.param.es_humidity_char_cccd);
        info.init_state++;
        break;
        
    case ENVIRONMENTAL_SENSING_SERVER_INIT_STATE_ES__IRRADIANCE_CCCD:
        environmental_sensing_server_set_cccd(ENVIRONMENTAL_SENSING_HDL_ES_IRRADIANCE_CCCD, info.param.es_irradiance_char_cccd);
        info.init_state++;
        break;
        
    case ENVIRONMENTAL_SENSING_SERVER_INIT_STATE_ES__POLLEN_CONCENTRATION_CCCD:
        environmental_sensing_server_set_cccd(ENVIRONMENTAL_SENSING_HDL_ES_POLLEN_CONCENTRATION_CCCD, info.param.es_pollen_concentration_char_cccd);
        info.init_state++;
        break;
        
    case ENVIRONMENTAL_SENSING_SERVER_INIT_STATE_ES__RAINFALL_CCCD:
        environmental_sensing_server_set_cccd(ENVIRONMENTAL_SENSING_HDL_ES_RAINFALL_CCCD, info.param.es_rainfall_char_cccd);
        info.init_state++;
        break;
        
    case ENVIRONMENTAL_SENSING_SERVER_INIT_STATE_ES__PRESSURE_CCCD:
        environmental_sensing_server_set_cccd(ENVIRONMENTAL_SENSING_HDL_ES_PRESSURE_CCCD, info.param.es_pressure_char_cccd);
        info.init_state++;
        break;
        
    case ENVIRONMENTAL_SENSING_SERVER_INIT_STATE_ES__TEMPERATURE_CCCD:
        environmental_sensing_server_set_cccd(ENVIRONMENTAL_SENSING_HDL_ES_TEMPERATURE_CCCD, info.param.es_temperature_char_cccd);
        info.init_state++;
        break;
        
    case ENVIRONMENTAL_SENSING_SERVER_INIT_STATE_ES__TRUE_WIND_DIRECTION_CCCD:
        environmental_sensing_server_set_cccd(ENVIRONMENTAL_SENSING_HDL_ES_TRUE_WIND_DIRECTION_CCCD, info.param.es_true_wind_direction_char_cccd);
        info.init_state++;
        break;
        
    case ENVIRONMENTAL_SENSING_SERVER_INIT_STATE_ES__TRUE_WIND_SPEED_CCCD:
        environmental_sensing_server_set_cccd(ENVIRONMENTAL_SENSING_HDL_ES_TRUE_WIND_SPEED_CCCD, info.param.es_true_wind_speed_char_cccd);
        info.init_state++;
        break;
        
    case ENVIRONMENTAL_SENSING_SERVER_INIT_STATE_ES__UV_INDEX_CCCD:
        environmental_sensing_server_set_cccd(ENVIRONMENTAL_SENSING_HDL_ES_UV_INDEX_CCCD, info.param.es_uv_index_char_cccd);
        info.init_state++;
        break;
        
    case ENVIRONMENTAL_SENSING_SERVER_INIT_STATE_ES__WIND_CHILL_CCCD:
        environmental_sensing_server_set_cccd(ENVIRONMENTAL_SENSING_HDL_ES_WIND_CHILL_CCCD, info.param.es_wind_chill_char_cccd);
        info.init_state++;
        break;
        
    case ENVIRONMENTAL_SENSING_SERVER_INIT_STATE_ES__BAROMETRIC_PRESSURE_TREND_CCCD:
        environmental_sensing_server_set_cccd(ENVIRONMENTAL_SENSING_HDL_ES_BAROMETRIC_PRESSURE_TREND_CCCD, info.param.es_barometric_pressure_trend_char_cccd);
        info.init_state++;
        break;
        
    case ENVIRONMENTAL_SENSING_SERVER_INIT_STATE_ES__MAGNETIC_DECLINATION_CCCD:
        environmental_sensing_server_set_cccd(ENVIRONMENTAL_SENSING_HDL_ES_MAGNETIC_DECLINATION_CCCD, info.param.es_magnetic_declination_char_cccd);
        info.init_state++;
        break;
        
    case ENVIRONMENTAL_SENSING_SERVER_INIT_STATE_ES__MAGNETIC_FLUX_DENSITY___2D_CCCD:
        environmental_sensing_server_set_cccd(ENVIRONMENTAL_SENSING_HDL_ES_MAGNETIC_FLUX_DENSITY___2D_CCCD, info.param.es_magnetic_flux_density___2d_char_cccd);
        info.init_state++;
        break;
        
    case ENVIRONMENTAL_SENSING_SERVER_INIT_STATE_ES__MAGNETIC_FLUX_DENSITY___3D_CCCD:
        environmental_sensing_server_set_cccd(ENVIRONMENTAL_SENSING_HDL_ES_MAGNETIC_FLUX_DENSITY___3D_CCCD, info.param.es_magnetic_flux_density___3d_char_cccd);
        info.init_state++;
        break;
        
    case ENVIRONMENTAL_SENSING_SERVER_INIT_STATE_BS__BATTERY_LEVEL_CCCD:
        environmental_sensing_server_set_cccd(ENVIRONMENTAL_SENSING_HDL_BS_BATTERY_LEVEL_CCCD, info.param.bs_battery_level_char_cccd);
        info.init_state++;
        break;
        
    case ENVIRONMENTAL_SENSING_SERVER_INIT_STATE_END:
        info.state  = ENVIRONMENTAL_SENSING_SERVER_STATE_CONNECTED;
        info.status = RBLE_OK;
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_ENABLE_COMP);
        now_set_data = FALSE;
        break;

    default:
        /* Unknown ENVIRONMENTAL_SENSING_SERVER init state */
        break;
    }
}

/* ##### GATT Functions ##### */
static void environmental_sensing_server_set_data(SET_DATA_INFO *sd_info)
{
    RBLE_GATT_SET_DATA data;

    info.hdl = sd_info->hdl;
    info.len = sd_info->len;
    memcpy(info.value, sd_info->value, sd_info->len);
    info.send_ntf_ind = sd_info->send_ntf_ind;
    info.write_cmd_ind = sd_info->write_cmd_ind;

    data.val_hdl = sd_info->hdl;
    data.val_len = sd_info->len;
    memcpy(data.value, sd_info->value, sd_info->len);

    now_set_data = TRUE;
    (void)RBLE_GATT_Set_Data(&data);
}

static void environmental_sensing_server_notify_request(uint16_t conhdl, uint16_t charhdl)
{
    RBLE_GATT_NOTIFY_REQ ntf;
    uint16_t cccd_param = 0;

    ntf.conhdl  = conhdl;
    ntf.charhdl = charhdl;

    switch( charhdl )
    {
    case ENVIRONMENTAL_SENSING_HDL_ES_APPARENT_WIND_DIRECTION_VAL:
        cccd_param = info.param.es_apparent_wind_direction_char_cccd & RBLE_PRF_START_NTF;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_APPARENT_WIND_SPEED_VAL:
        cccd_param = info.param.es_apparent_wind_speed_char_cccd & RBLE_PRF_START_NTF;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_DEW_POINT_VAL:
        cccd_param = info.param.es_dew_point_char_cccd & RBLE_PRF_START_NTF;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_ELEVATION_VAL:
        cccd_param = info.param.es_elevation_char_cccd & RBLE_PRF_START_NTF;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_GUST_FACTOR_VAL:
        cccd_param = info.param.es_gust_factor_char_cccd & RBLE_PRF_START_NTF;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_HEAT_INDEX_VAL:
        cccd_param = info.param.es_heat_index_char_cccd & RBLE_PRF_START_NTF;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_HUMIDITY_VAL:
        cccd_param = info.param.es_humidity_char_cccd & RBLE_PRF_START_NTF;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_IRRADIANCE_VAL:
        cccd_param = info.param.es_irradiance_char_cccd & RBLE_PRF_START_NTF;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_POLLEN_CONCENTRATION_VAL:
        cccd_param = info.param.es_pollen_concentration_char_cccd & RBLE_PRF_START_NTF;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_RAINFALL_VAL:
        cccd_param = info.param.es_rainfall_char_cccd & RBLE_PRF_START_NTF;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_PRESSURE_VAL:
        cccd_param = info.param.es_pressure_char_cccd & RBLE_PRF_START_NTF;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_TEMPERATURE_VAL:
        cccd_param = info.param.es_temperature_char_cccd & RBLE_PRF_START_NTF;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_TRUE_WIND_DIRECTION_VAL:
        cccd_param = info.param.es_true_wind_direction_char_cccd & RBLE_PRF_START_NTF;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_TRUE_WIND_SPEED_VAL:
        cccd_param = info.param.es_true_wind_speed_char_cccd & RBLE_PRF_START_NTF;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_UV_INDEX_VAL:
        cccd_param = info.param.es_uv_index_char_cccd & RBLE_PRF_START_NTF;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_WIND_CHILL_VAL:
        cccd_param = info.param.es_wind_chill_char_cccd & RBLE_PRF_START_NTF;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_BAROMETRIC_PRESSURE_TREND_VAL:
        cccd_param = info.param.es_barometric_pressure_trend_char_cccd & RBLE_PRF_START_NTF;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_MAGNETIC_DECLINATION_VAL:
        cccd_param = info.param.es_magnetic_declination_char_cccd & RBLE_PRF_START_NTF;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_MAGNETIC_FLUX_DENSITY___2D_VAL:
        cccd_param = info.param.es_magnetic_flux_density___2d_char_cccd & RBLE_PRF_START_NTF;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_MAGNETIC_FLUX_DENSITY___3D_VAL:
        cccd_param = info.param.es_magnetic_flux_density___3d_char_cccd & RBLE_PRF_START_NTF;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_BS_BATTERY_LEVEL_VAL:
        cccd_param = info.param.bs_battery_level_char_cccd & RBLE_PRF_START_NTF;
        break;
        
    default:
        /* Unsupported hdl */
        break;
    }

    if( cccd_param == RBLE_PRF_STOP_NTFIND )
    {
        info.status = RBLE_GATT_NOTIFY_NOT_ALLOWED;
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_NOTIFY_COMP);
        if( queue_ct > 0 )
        {
            SET_DATA_INFO data;
            
            environmental_sensing_server_set_data_queue_read(&data);
            environmental_sensing_server_set_data(&data);
        }
        else
        {
            now_set_data = FALSE;
        }
    }
    else
    {
        (void)RBLE_GATT_Notify_Request(&ntf);
    }
}

static void environmental_sensing_server_indicate_request(uint16_t conhdl, uint16_t charhdl)
{
    RBLE_GATT_INDICATE_REQ ind;
    uint16_t cccd_param;

    ind.conhdl  = conhdl;
    ind.charhdl = charhdl;

    switch( charhdl )
    {
    case ENVIRONMENTAL_SENSING_HDL_ES_DESCRIPTOR_VALUE_CHANGED_VAL:
        cccd_param = info.param.es_descriptor_value_changed_char_cccd & RBLE_PRF_START_IND;
        break;
        
    default:
        /* Unsupported hdl */
        break;
    }

    if( cccd_param == RBLE_PRF_STOP_NTFIND )
    {
        info.status = RBLE_GATT_INDICATE_NOT_ALLOWED;
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_INDICATE_COMP);
        if( queue_ct > 0 )
        {
            SET_DATA_INFO data;
            
            environmental_sensing_server_set_data_queue_read(&data);
            environmental_sensing_server_set_data(&data);
        }
        else
        {
            now_set_data = FALSE;
        }
    }
    else
    {
        (void)RBLE_GATT_Indicate_Request(&ind);
    }
}
static void environmental_sensing_server_write_resp(BOOL flg)
{
    RBLE_GATT_WRITE_RESP resp;

    if (TRUE == info.write_cmd_ind) {
        resp.conhdl   = info.conhdl;
        resp.att_hdl  = info.hdl;
        if( flg == TRUE )
        {
            resp.att_code = info.status;
        }
        else
        {
            resp.att_code = RBLE_ATT_ERR_QUEUE_FULL;
        }
        (void)RBLE_GATT_Write_Response(&resp);
    }
}

/* ##### GATT Event Handlers ##### */
static void environmental_sensing_server_set_data_cmp_handler(RBLE_GATT_EVENT *event)
{
    struct RBLE_GATT_Set_Data_Complete_t *result =
        (struct RBLE_GATT_Set_Data_Complete_t *)&event->param.set_data_cmp;

    info.status = result->status;

    if (ENVIRONMENTAL_SENSING_SERVER_STATE_INIT == info.state) {
        now_set_data = FALSE;
        environmental_sensing_server_set_init_data();
        return;
    }

    switch(info.hdl)
    {
    case ENVIRONMENTAL_SENSING_HDL_ES_DESCRIPTOR_VALUE_CHANGED_VAL:
        if( ENVIRONMENTAL_SENSING_SERVER_DESC_IND_ENABLE == info.send_ntf_ind )
        {
            environmental_sensing_server_indicate_request(info.conhdl, info.hdl);
            return;
        }
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_SET_VALUE_COMP);
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_DESCRIPTOR_VALUE_CHANGED_CCCD:
        environmental_sensing_server_write_resp(TRUE);
        info.param.es_descriptor_value_changed_char_cccd = (uint16_t)((info.value[1] << 8) | info.value[0]);
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_CCCD_WRITE);
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_APPARENT_WIND_DIRECTION_VAL:
        if( ENVIRONMENTAL_SENSING_SERVER_DESC_NTF_ENABLE == info.send_ntf_ind )
        {
            environmental_sensing_server_notify_request(info.conhdl, info.hdl);
            return;
        }
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_SET_VALUE_COMP);
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_APPARENT_WIND_DIRECTION_CCCD:
        environmental_sensing_server_write_resp(TRUE);
        info.param.es_apparent_wind_direction_char_cccd = (uint16_t)((info.value[1] << 8) | info.value[0]);
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_CCCD_WRITE);
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_APPARENT_WIND_SPEED_VAL:
        if( ENVIRONMENTAL_SENSING_SERVER_DESC_NTF_ENABLE == info.send_ntf_ind )
        {
            environmental_sensing_server_notify_request(info.conhdl, info.hdl);
            return;
        }
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_SET_VALUE_COMP);
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_APPARENT_WIND_SPEED_CCCD:
        environmental_sensing_server_write_resp(TRUE);
        info.param.es_apparent_wind_speed_char_cccd = (uint16_t)((info.value[1] << 8) | info.value[0]);
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_CCCD_WRITE);
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_DEW_POINT_VAL:
        if( ENVIRONMENTAL_SENSING_SERVER_DESC_NTF_ENABLE == info.send_ntf_ind )
        {
            environmental_sensing_server_notify_request(info.conhdl, info.hdl);
            return;
        }
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_SET_VALUE_COMP);
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_DEW_POINT_CCCD:
        environmental_sensing_server_write_resp(TRUE);
        info.param.es_dew_point_char_cccd = (uint16_t)((info.value[1] << 8) | info.value[0]);
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_CCCD_WRITE);
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_ELEVATION_VAL:
        if( ENVIRONMENTAL_SENSING_SERVER_DESC_NTF_ENABLE == info.send_ntf_ind )
        {
            environmental_sensing_server_notify_request(info.conhdl, info.hdl);
            return;
        }
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_SET_VALUE_COMP);
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_ELEVATION_CCCD:
        environmental_sensing_server_write_resp(TRUE);
        info.param.es_elevation_char_cccd = (uint16_t)((info.value[1] << 8) | info.value[0]);
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_CCCD_WRITE);
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_GUST_FACTOR_VAL:
        if( ENVIRONMENTAL_SENSING_SERVER_DESC_NTF_ENABLE == info.send_ntf_ind )
        {
            environmental_sensing_server_notify_request(info.conhdl, info.hdl);
            return;
        }
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_SET_VALUE_COMP);
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_GUST_FACTOR_CCCD:
        environmental_sensing_server_write_resp(TRUE);
        info.param.es_gust_factor_char_cccd = (uint16_t)((info.value[1] << 8) | info.value[0]);
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_CCCD_WRITE);
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_HEAT_INDEX_VAL:
        if( ENVIRONMENTAL_SENSING_SERVER_DESC_NTF_ENABLE == info.send_ntf_ind )
        {
            environmental_sensing_server_notify_request(info.conhdl, info.hdl);
            return;
        }
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_SET_VALUE_COMP);
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_HEAT_INDEX_CCCD:
        environmental_sensing_server_write_resp(TRUE);
        info.param.es_heat_index_char_cccd = (uint16_t)((info.value[1] << 8) | info.value[0]);
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_CCCD_WRITE);
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_HUMIDITY_VAL:
        if( ENVIRONMENTAL_SENSING_SERVER_DESC_NTF_ENABLE == info.send_ntf_ind )
        {
            environmental_sensing_server_notify_request(info.conhdl, info.hdl);
            return;
        }
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_SET_VALUE_COMP);
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_HUMIDITY_CCCD:
        environmental_sensing_server_write_resp(TRUE);
        info.param.es_humidity_char_cccd = (uint16_t)((info.value[1] << 8) | info.value[0]);
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_CCCD_WRITE);
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_IRRADIANCE_VAL:
        if( ENVIRONMENTAL_SENSING_SERVER_DESC_NTF_ENABLE == info.send_ntf_ind )
        {
            environmental_sensing_server_notify_request(info.conhdl, info.hdl);
            return;
        }
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_SET_VALUE_COMP);
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_IRRADIANCE_CCCD:
        environmental_sensing_server_write_resp(TRUE);
        info.param.es_irradiance_char_cccd = (uint16_t)((info.value[1] << 8) | info.value[0]);
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_CCCD_WRITE);
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_POLLEN_CONCENTRATION_VAL:
        if( ENVIRONMENTAL_SENSING_SERVER_DESC_NTF_ENABLE == info.send_ntf_ind )
        {
            environmental_sensing_server_notify_request(info.conhdl, info.hdl);
            return;
        }
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_SET_VALUE_COMP);
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_POLLEN_CONCENTRATION_CCCD:
        environmental_sensing_server_write_resp(TRUE);
        info.param.es_pollen_concentration_char_cccd = (uint16_t)((info.value[1] << 8) | info.value[0]);
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_CCCD_WRITE);
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_RAINFALL_VAL:
        if( ENVIRONMENTAL_SENSING_SERVER_DESC_NTF_ENABLE == info.send_ntf_ind )
        {
            environmental_sensing_server_notify_request(info.conhdl, info.hdl);
            return;
        }
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_SET_VALUE_COMP);
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_RAINFALL_CCCD:
        environmental_sensing_server_write_resp(TRUE);
        info.param.es_rainfall_char_cccd = (uint16_t)((info.value[1] << 8) | info.value[0]);
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_CCCD_WRITE);
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_PRESSURE_VAL:
        if( ENVIRONMENTAL_SENSING_SERVER_DESC_NTF_ENABLE == info.send_ntf_ind )
        {
            environmental_sensing_server_notify_request(info.conhdl, info.hdl);
            return;
        }
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_SET_VALUE_COMP);
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_PRESSURE_CCCD:
        environmental_sensing_server_write_resp(TRUE);
        info.param.es_pressure_char_cccd = (uint16_t)((info.value[1] << 8) | info.value[0]);
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_CCCD_WRITE);
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_TEMPERATURE_VAL:
        if( ENVIRONMENTAL_SENSING_SERVER_DESC_NTF_ENABLE == info.send_ntf_ind )
        {
            environmental_sensing_server_notify_request(info.conhdl, info.hdl);
            return;
        }
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_SET_VALUE_COMP);
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_TEMPERATURE_CCCD:
        environmental_sensing_server_write_resp(TRUE);
        info.param.es_temperature_char_cccd = (uint16_t)((info.value[1] << 8) | info.value[0]);
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_CCCD_WRITE);
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_TRUE_WIND_DIRECTION_VAL:
        if( ENVIRONMENTAL_SENSING_SERVER_DESC_NTF_ENABLE == info.send_ntf_ind )
        {
            environmental_sensing_server_notify_request(info.conhdl, info.hdl);
            return;
        }
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_SET_VALUE_COMP);
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_TRUE_WIND_DIRECTION_CCCD:
        environmental_sensing_server_write_resp(TRUE);
        info.param.es_true_wind_direction_char_cccd = (uint16_t)((info.value[1] << 8) | info.value[0]);
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_CCCD_WRITE);
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_TRUE_WIND_SPEED_VAL:
        if( ENVIRONMENTAL_SENSING_SERVER_DESC_NTF_ENABLE == info.send_ntf_ind )
        {
            environmental_sensing_server_notify_request(info.conhdl, info.hdl);
            return;
        }
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_SET_VALUE_COMP);
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_TRUE_WIND_SPEED_CCCD:
        environmental_sensing_server_write_resp(TRUE);
        info.param.es_true_wind_speed_char_cccd = (uint16_t)((info.value[1] << 8) | info.value[0]);
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_CCCD_WRITE);
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_UV_INDEX_VAL:
        if( ENVIRONMENTAL_SENSING_SERVER_DESC_NTF_ENABLE == info.send_ntf_ind )
        {
            environmental_sensing_server_notify_request(info.conhdl, info.hdl);
            return;
        }
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_SET_VALUE_COMP);
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_UV_INDEX_CCCD:
        environmental_sensing_server_write_resp(TRUE);
        info.param.es_uv_index_char_cccd = (uint16_t)((info.value[1] << 8) | info.value[0]);
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_CCCD_WRITE);
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_WIND_CHILL_VAL:
        if( ENVIRONMENTAL_SENSING_SERVER_DESC_NTF_ENABLE == info.send_ntf_ind )
        {
            environmental_sensing_server_notify_request(info.conhdl, info.hdl);
            return;
        }
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_SET_VALUE_COMP);
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_WIND_CHILL_CCCD:
        environmental_sensing_server_write_resp(TRUE);
        info.param.es_wind_chill_char_cccd = (uint16_t)((info.value[1] << 8) | info.value[0]);
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_CCCD_WRITE);
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_BAROMETRIC_PRESSURE_TREND_VAL:
        if( ENVIRONMENTAL_SENSING_SERVER_DESC_NTF_ENABLE == info.send_ntf_ind )
        {
            environmental_sensing_server_notify_request(info.conhdl, info.hdl);
            return;
        }
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_SET_VALUE_COMP);
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_BAROMETRIC_PRESSURE_TREND_CCCD:
        environmental_sensing_server_write_resp(TRUE);
        info.param.es_barometric_pressure_trend_char_cccd = (uint16_t)((info.value[1] << 8) | info.value[0]);
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_CCCD_WRITE);
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_MAGNETIC_DECLINATION_VAL:
        if( ENVIRONMENTAL_SENSING_SERVER_DESC_NTF_ENABLE == info.send_ntf_ind )
        {
            environmental_sensing_server_notify_request(info.conhdl, info.hdl);
            return;
        }
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_SET_VALUE_COMP);
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_MAGNETIC_DECLINATION_CCCD:
        environmental_sensing_server_write_resp(TRUE);
        info.param.es_magnetic_declination_char_cccd = (uint16_t)((info.value[1] << 8) | info.value[0]);
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_CCCD_WRITE);
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_MAGNETIC_FLUX_DENSITY___2D_VAL:
        if( ENVIRONMENTAL_SENSING_SERVER_DESC_NTF_ENABLE == info.send_ntf_ind )
        {
            environmental_sensing_server_notify_request(info.conhdl, info.hdl);
            return;
        }
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_SET_VALUE_COMP);
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_MAGNETIC_FLUX_DENSITY___2D_CCCD:
        environmental_sensing_server_write_resp(TRUE);
        info.param.es_magnetic_flux_density___2d_char_cccd = (uint16_t)((info.value[1] << 8) | info.value[0]);
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_CCCD_WRITE);
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_MAGNETIC_FLUX_DENSITY___3D_VAL:
        if( ENVIRONMENTAL_SENSING_SERVER_DESC_NTF_ENABLE == info.send_ntf_ind )
        {
            environmental_sensing_server_notify_request(info.conhdl, info.hdl);
            return;
        }
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_SET_VALUE_COMP);
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_MAGNETIC_FLUX_DENSITY___3D_CCCD:
        environmental_sensing_server_write_resp(TRUE);
        info.param.es_magnetic_flux_density___3d_char_cccd = (uint16_t)((info.value[1] << 8) | info.value[0]);
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_CCCD_WRITE);
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_DI_MANUFACTURER_NAME_STRING_VAL:
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_SET_VALUE_COMP);
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_DI_MODEL_NUMBER_STRING_VAL:
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_SET_VALUE_COMP);
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_DI_SERIAL_NUMBER_STRING_VAL:
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_SET_VALUE_COMP);
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_DI_HARDWARE_REVISION_STRING_VAL:
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_SET_VALUE_COMP);
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_DI_FIRMWARE_REVISION_STRING_VAL:
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_SET_VALUE_COMP);
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_DI_SOFTWARE_REVISION_STRING_VAL:
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_SET_VALUE_COMP);
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_DI_SYSTEM_ID_VAL:
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_SET_VALUE_COMP);
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_DI_IEEE_11073_20601_REGULATORY_CERTIFICATION_DATA_LIST_VAL:
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_SET_VALUE_COMP);
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_DI_PNP_ID_VAL:
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_SET_VALUE_COMP);
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_BS_BATTERY_LEVEL_VAL:
        if( ENVIRONMENTAL_SENSING_SERVER_DESC_NTF_ENABLE == info.send_ntf_ind )
        {
            environmental_sensing_server_notify_request(info.conhdl, info.hdl);
            return;
        }
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_SET_VALUE_COMP);
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_BS_BATTERY_LEVEL_CCCD:
        environmental_sensing_server_write_resp(TRUE);
        info.param.bs_battery_level_char_cccd = (uint16_t)((info.value[1] << 8) | info.value[0]);
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_CCCD_WRITE);
        break;
        
    default:
        /* Unsupported hdl */
        break;
    }

    /* Next Set_Data check */
    if( queue_ct > 0 )
    {
        SET_DATA_INFO data;
        
        environmental_sensing_server_set_data_queue_read( &data );
        environmental_sensing_server_set_data( &data );
    }
    else
    {
        now_set_data = FALSE;
    }
}

static void environmental_sensing_server_write_cmd_ind_handler(RBLE_GATT_EVENT *event)
{
    struct RBLE_GATT_Write_Cmd_Ind_t *result =
        (struct RBLE_GATT_Write_Cmd_Ind_t *)&event->param.write_cmd_ind;
    SET_DATA_INFO data;

    data.hdl           = result->elmt;
    data.len           = result->size;
    data.write_cmd_ind = result->resp;
    data.send_ntf_ind  = ENVIRONMENTAL_SENSING_SERVER_DESC_ALL_DISABLE;

    memset(data.value, 0, data.len);

    switch (result->elmt) {
    case ENVIRONMENTAL_SENSING_HDL_ES_DESCRIPTOR_VALUE_CHANGED_CCCD:
        data.value[0] = (uint8_t)(result->value[0] & (RBLE_PRF_START_NTF | RBLE_PRF_START_IND));
        data.value[1] = result->value[1];
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_APPARENT_WIND_DIRECTION_CCCD:
        data.value[0] = (uint8_t)(result->value[0] & (RBLE_PRF_START_NTF | RBLE_PRF_START_IND));
        data.value[1] = result->value[1];
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_APPARENT_WIND_SPEED_CCCD:
        data.value[0] = (uint8_t)(result->value[0] & (RBLE_PRF_START_NTF | RBLE_PRF_START_IND));
        data.value[1] = result->value[1];
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_DEW_POINT_CCCD:
        data.value[0] = (uint8_t)(result->value[0] & (RBLE_PRF_START_NTF | RBLE_PRF_START_IND));
        data.value[1] = result->value[1];
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_ELEVATION_CCCD:
        data.value[0] = (uint8_t)(result->value[0] & (RBLE_PRF_START_NTF | RBLE_PRF_START_IND));
        data.value[1] = result->value[1];
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_GUST_FACTOR_CCCD:
        data.value[0] = (uint8_t)(result->value[0] & (RBLE_PRF_START_NTF | RBLE_PRF_START_IND));
        data.value[1] = result->value[1];
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_HEAT_INDEX_CCCD:
        data.value[0] = (uint8_t)(result->value[0] & (RBLE_PRF_START_NTF | RBLE_PRF_START_IND));
        data.value[1] = result->value[1];
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_HUMIDITY_CCCD:
        data.value[0] = (uint8_t)(result->value[0] & (RBLE_PRF_START_NTF | RBLE_PRF_START_IND));
        data.value[1] = result->value[1];
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_IRRADIANCE_CCCD:
        data.value[0] = (uint8_t)(result->value[0] & (RBLE_PRF_START_NTF | RBLE_PRF_START_IND));
        data.value[1] = result->value[1];
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_POLLEN_CONCENTRATION_CCCD:
        data.value[0] = (uint8_t)(result->value[0] & (RBLE_PRF_START_NTF | RBLE_PRF_START_IND));
        data.value[1] = result->value[1];
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_RAINFALL_CCCD:
        data.value[0] = (uint8_t)(result->value[0] & (RBLE_PRF_START_NTF | RBLE_PRF_START_IND));
        data.value[1] = result->value[1];
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_PRESSURE_CCCD:
        data.value[0] = (uint8_t)(result->value[0] & (RBLE_PRF_START_NTF | RBLE_PRF_START_IND));
        data.value[1] = result->value[1];
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_TEMPERATURE_CCCD:
        data.value[0] = (uint8_t)(result->value[0] & (RBLE_PRF_START_NTF | RBLE_PRF_START_IND));
        data.value[1] = result->value[1];
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_TRUE_WIND_DIRECTION_CCCD:
        data.value[0] = (uint8_t)(result->value[0] & (RBLE_PRF_START_NTF | RBLE_PRF_START_IND));
        data.value[1] = result->value[1];
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_TRUE_WIND_SPEED_CCCD:
        data.value[0] = (uint8_t)(result->value[0] & (RBLE_PRF_START_NTF | RBLE_PRF_START_IND));
        data.value[1] = result->value[1];
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_UV_INDEX_CCCD:
        data.value[0] = (uint8_t)(result->value[0] & (RBLE_PRF_START_NTF | RBLE_PRF_START_IND));
        data.value[1] = result->value[1];
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_WIND_CHILL_CCCD:
        data.value[0] = (uint8_t)(result->value[0] & (RBLE_PRF_START_NTF | RBLE_PRF_START_IND));
        data.value[1] = result->value[1];
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_BAROMETRIC_PRESSURE_TREND_CCCD:
        data.value[0] = (uint8_t)(result->value[0] & (RBLE_PRF_START_NTF | RBLE_PRF_START_IND));
        data.value[1] = result->value[1];
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_MAGNETIC_DECLINATION_CCCD:
        data.value[0] = (uint8_t)(result->value[0] & (RBLE_PRF_START_NTF | RBLE_PRF_START_IND));
        data.value[1] = result->value[1];
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_MAGNETIC_FLUX_DENSITY___2D_CCCD:
        data.value[0] = (uint8_t)(result->value[0] & (RBLE_PRF_START_NTF | RBLE_PRF_START_IND));
        data.value[1] = result->value[1];
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_MAGNETIC_FLUX_DENSITY___3D_CCCD:
        data.value[0] = (uint8_t)(result->value[0] & (RBLE_PRF_START_NTF | RBLE_PRF_START_IND));
        data.value[1] = result->value[1];
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_BS_BATTERY_LEVEL_CCCD:
        data.value[0] = (uint8_t)(result->value[0] & (RBLE_PRF_START_NTF | RBLE_PRF_START_IND));
        data.value[1] = result->value[1];
        break;
        
    default:
        /* Unsupported hdl */
        break;
    }

    if( !(environmental_sensing_server_set_data_queueing(&data)) )
    {
        RBLE_GATT_WRITE_RESP resp;

        if( data.write_cmd_ind == TRUE )
        {
            resp.conhdl   = result->conhdl;
            resp.att_hdl  = result->elmt;
            resp.att_code = RBLE_ATT_ERR_QUEUE_FULL;
            (void)RBLE_GATT_Write_Response(&resp);
        }
    }
}

static void environmental_sensing_server_handle_value_cfm_handler(RBLE_GATT_EVENT *event)
{
    struct RBLE_GATT_Handle_Value_Cfm_t *result =
        (struct RBLE_GATT_Handle_Value_Cfm_t *)&event->param.handle_value_cfm;

    info.status = result->status;

    switch(info.hdl)
    {
    case ENVIRONMENTAL_SENSING_HDL_ES_DESCRIPTOR_VALUE_CHANGED_VAL:
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_INDICATE_COMP);
        break;
        
    default:
        /* Unsupported hdl */
        break;
    }
    
    if( queue_ct > 0 )
    {
        SET_DATA_INFO data;
        
        environmental_sensing_server_set_data_queue_read( &data );
        environmental_sensing_server_set_data( &data );
    }
    else
    {
        now_set_data = FALSE;
    }
}

static void environmental_sensing_server_notify_comp_handler(RBLE_GATT_EVENT *event)
{
    struct RBLE_GATT_Notify_Comp_t *result =
        (struct RBLE_GATT_Notify_Comp_t *)&event->param.notify_cmp;

    info.status = result->status;
    info.hdl = result->charhdl;

    switch(info.hdl)
    {
    case ENVIRONMENTAL_SENSING_HDL_ES_APPARENT_WIND_DIRECTION_VAL:
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_NOTIFY_COMP);
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_APPARENT_WIND_SPEED_VAL:
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_NOTIFY_COMP);
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_DEW_POINT_VAL:
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_NOTIFY_COMP);
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_ELEVATION_VAL:
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_NOTIFY_COMP);
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_GUST_FACTOR_VAL:
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_NOTIFY_COMP);
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_HEAT_INDEX_VAL:
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_NOTIFY_COMP);
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_HUMIDITY_VAL:
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_NOTIFY_COMP);
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_IRRADIANCE_VAL:
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_NOTIFY_COMP);
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_POLLEN_CONCENTRATION_VAL:
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_NOTIFY_COMP);
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_RAINFALL_VAL:
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_NOTIFY_COMP);
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_PRESSURE_VAL:
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_NOTIFY_COMP);
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_TEMPERATURE_VAL:
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_NOTIFY_COMP);
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_TRUE_WIND_DIRECTION_VAL:
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_NOTIFY_COMP);
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_TRUE_WIND_SPEED_VAL:
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_NOTIFY_COMP);
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_UV_INDEX_VAL:
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_NOTIFY_COMP);
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_WIND_CHILL_VAL:
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_NOTIFY_COMP);
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_BAROMETRIC_PRESSURE_TREND_VAL:
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_NOTIFY_COMP);
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_MAGNETIC_DECLINATION_VAL:
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_NOTIFY_COMP);
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_MAGNETIC_FLUX_DENSITY___2D_VAL:
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_NOTIFY_COMP);
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_MAGNETIC_FLUX_DENSITY___3D_VAL:
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_NOTIFY_COMP);
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_BS_BATTERY_LEVEL_VAL:
        environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_NOTIFY_COMP);
        break;
        
    default:
        /* Unsupported hdl */
        break;
    }
    
    if( queue_ct > 0 )
    {
        SET_DATA_INFO data;
        
        environmental_sensing_server_set_data_queue_read( &data );
        environmental_sensing_server_set_data( &data );
    }
    else
    {
        now_set_data = FALSE;
    }
}
static void environmental_sensing_server_gatt_callback(RBLE_GATT_EVENT *event)
{
    switch (event->type) {
    case RBLE_GATT_EVENT_SET_DATA_CMP:
        environmental_sensing_server_set_data_cmp_handler(event);
        break;

    case RBLE_GATT_EVENT_WRITE_CMD_IND:
        environmental_sensing_server_write_cmd_ind_handler(event);
        break;

    case RBLE_GATT_EVENT_HANDLE_VALUE_CFM:
        environmental_sensing_server_handle_value_cfm_handler(event);
        break;
        
    case RBLE_GATT_EVENT_NOTIFY_COMP:
        environmental_sensing_server_notify_comp_handler(event);
        break;
        
    default:
        /* Unsupported GATT event */
        break;
    }
}

static BOOL environmental_sensing_server_set_data_queueing(SET_DATA_INFO *data)
{
    if( queue_ct >= QUEUE_MAX )
    {
        /* Queueing buffer full */
        return FALSE;
    }
    
    if( now_set_data == TRUE )
    {
        /* Set_Data is running -> Queueing */
        
        /* Queueing data count increment */
        queue_ct++;
        
        /* Queueing data set */
        queue[queue_w_p].hdl = data->hdl;
        queue[queue_w_p].len = data->len;
        memcpy(queue[queue_w_p].value, data->value, data->len);
        queue[queue_w_p].send_ntf_ind = data->send_ntf_ind;
        queue[queue_w_p].write_cmd_ind = data->write_cmd_ind;
        
        /* Queueing write pointer increment */
        queue_w_p++;
        if( queue_w_p >= QUEUE_MAX )
        {
            queue_w_p = 0;
        }
    }
    else
    {
        /* Set_Data is not running -> Set_Data execution */
        SET_DATA_INFO sd_info;
        
        sd_info.hdl = data->hdl;
        sd_info.len = data->len;
        memcpy(sd_info.value, data->value, data->len);
        sd_info.send_ntf_ind = data->send_ntf_ind;
        sd_info.write_cmd_ind = data->write_cmd_ind;

        environmental_sensing_server_set_data( &sd_info );
    }
    
    return TRUE;
}

static BOOL environmental_sensing_server_set_data_queue_read(SET_DATA_INFO *data)
{
    if( queue_ct == 0 )
    {
        /* Queueing buffer empty */
        return FALSE;
    }
    
    /* Queueing data count decrement */
    queue_ct--;
    
    /* Queueing data pop */
    data->hdl = queue[queue_r_p].hdl;
    data->len = queue[queue_r_p].len;
    memcpy(data->value, queue[queue_r_p].value, data->len);
    data->send_ntf_ind = queue[queue_r_p].send_ntf_ind;
    data->write_cmd_ind = queue[queue_r_p].write_cmd_ind;
    
    /* Queieing read pointer increment */
    queue_r_p++;
    if( queue_r_p >= QUEUE_MAX )
    {
        queue_r_p = 0;
    }

    return TRUE;
}


/*******************************************************************************
 * Function Definitions (API)
 ******************************************************************************/
RBLE_STATUS ENVIRONMENTAL_SENSING_Server_Enable(uint16_t conhdl, uint8_t con_type,
                                 ENVIRONMENTAL_SENSING_SERVER_PARAM *param, ENVIRONMENTAL_SENSING_SERVER_EVENT_HANDLER callback)
{
    RBLE_STATUS status;

    if (!callback || !param) {
        return RBLE_PARAM_ERR;
    }

    if (ENVIRONMENTAL_SENSING_SERVER_STATE_IDLE != info.state) {
        return RBLE_STATUS_ERROR;
    }

    status = RBLE_GATT_Enable(&environmental_sensing_server_gatt_callback);
    if (RBLE_OK != status) {
        return RBLE_STATUS_ERROR;
    }

    memset(&info, 0, sizeof(info));

    info.conhdl     = conhdl;
    info.callback   = callback;
    info.state      = ENVIRONMENTAL_SENSING_SERVER_STATE_INIT;
    info.init_state = ENVIRONMENTAL_SENSING_SERVER_INIT_STATE_ES__DESCRIPTOR_VALUE_CHANGED_CCCD;

    if (RBLE_PRF_CON_NORMAL == con_type) {
		info.param.es_descriptor_value_changed_char_cccd = param->es_descriptor_value_changed_char_cccd;
		info.param.es_apparent_wind_direction_char_cccd = param->es_apparent_wind_direction_char_cccd;
		info.param.es_apparent_wind_speed_char_cccd = param->es_apparent_wind_speed_char_cccd;
		info.param.es_dew_point_char_cccd = param->es_dew_point_char_cccd;
		info.param.es_elevation_char_cccd = param->es_elevation_char_cccd;
		info.param.es_gust_factor_char_cccd = param->es_gust_factor_char_cccd;
		info.param.es_heat_index_char_cccd = param->es_heat_index_char_cccd;
		info.param.es_humidity_char_cccd = param->es_humidity_char_cccd;
		info.param.es_irradiance_char_cccd = param->es_irradiance_char_cccd;
		info.param.es_pollen_concentration_char_cccd = param->es_pollen_concentration_char_cccd;
		info.param.es_rainfall_char_cccd = param->es_rainfall_char_cccd;
		info.param.es_pressure_char_cccd = param->es_pressure_char_cccd;
		info.param.es_temperature_char_cccd = param->es_temperature_char_cccd;
		info.param.es_true_wind_direction_char_cccd = param->es_true_wind_direction_char_cccd;
		info.param.es_true_wind_speed_char_cccd = param->es_true_wind_speed_char_cccd;
		info.param.es_uv_index_char_cccd = param->es_uv_index_char_cccd;
		info.param.es_wind_chill_char_cccd = param->es_wind_chill_char_cccd;
		info.param.es_barometric_pressure_trend_char_cccd = param->es_barometric_pressure_trend_char_cccd;
		info.param.es_magnetic_declination_char_cccd = param->es_magnetic_declination_char_cccd;
		info.param.es_magnetic_flux_density___2d_char_cccd = param->es_magnetic_flux_density___2d_char_cccd;
		info.param.es_magnetic_flux_density___3d_char_cccd = param->es_magnetic_flux_density___3d_char_cccd;
		info.param.bs_battery_level_char_cccd = param->bs_battery_level_char_cccd;
    }

    environmental_sensing_server_set_init_data();

    return RBLE_OK;
}

RBLE_STATUS ENVIRONMENTAL_SENSING_Server_Disable(uint16_t conhdl)
{
    if (info.conhdl != conhdl) {
        return RBLE_PARAM_ERR;
    }

    if (ENVIRONMENTAL_SENSING_SERVER_STATE_CONNECTED != info.state) {
        return RBLE_STATUS_ERROR;
    }

    if( queue_ct > 0 )
    {
        return RBLE_BUSY;
    }

    info.state = ENVIRONMENTAL_SENSING_SERVER_STATE_IDLE;

    info.status = RBLE_OK;
    environmental_sensing_server_send_event(ENVIRONMENTAL_SENSING_SERVER_EVENT_DISABLE_COMP);

    return RBLE_OK;
}

RBLE_STATUS ENVIRONMENTAL_SENSING_Server_Char_NtfInd(uint16_t conhdl, uint16_t char_hdl, uint8_t *char_val, uint16_t req_type)
{
    uint16_t len = 0;
    SET_DATA_INFO data;
    
    if (info.conhdl != conhdl) {
        return RBLE_PARAM_ERR;
    }

    if( (req_type != ENVIRONMENTAL_SENSING_SERVER_DESC_NTF_ENABLE) && 
        (req_type != ENVIRONMENTAL_SENSING_SERVER_DESC_IND_ENABLE) )
    {
        return RBLE_PARAM_ERR;
    }

    if( NULL == char_val )
    {
        return RBLE_PARAM_ERR;
    }

    if (ENVIRONMENTAL_SENSING_SERVER_STATE_CONNECTED != info.state) {
        return RBLE_STATUS_ERROR;
    }

    switch( char_hdl )
    {
    case ENVIRONMENTAL_SENSING_HDL_ES_DESCRIPTOR_VALUE_CHANGED_VAL:
		len = 1;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_APPARENT_WIND_DIRECTION_VAL:
        len = 2;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_APPARENT_WIND_SPEED_VAL:
        len = 2;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_DEW_POINT_VAL:
        len = 1;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_ELEVATION_VAL:
        len = 3;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_GUST_FACTOR_VAL:
        len = 1;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_HEAT_INDEX_VAL:
        len = 1;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_HUMIDITY_VAL:
        len = 2;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_IRRADIANCE_VAL:
        len = 2;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_POLLEN_CONCENTRATION_VAL:
        len = 3;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_RAINFALL_VAL:
        len = 2;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_PRESSURE_VAL:
        len = 4;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_TEMPERATURE_VAL:
        len = 2;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_TRUE_WIND_DIRECTION_VAL:
        len = 2;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_TRUE_WIND_SPEED_VAL:
        len = 2;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_UV_INDEX_VAL:
        len = 1;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_WIND_CHILL_VAL:
        len = 1;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_BAROMETRIC_PRESSURE_TREND_VAL:
        len = 1;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_MAGNETIC_DECLINATION_VAL:
        len = 2;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_MAGNETIC_FLUX_DENSITY___2D_VAL:
        len = 4;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_MAGNETIC_FLUX_DENSITY___3D_VAL:
        len = 6;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_BS_BATTERY_LEVEL_VAL:
        len = 1;
        break;
        
    default:
        return RBLE_PARAM_ERR;
    }
    
    data.hdl = char_hdl;
    data.len = len;
    memcpy(data.value, char_val, data.len);
    data.send_ntf_ind = req_type;
    data.write_cmd_ind = FALSE;
    if( FALSE == environmental_sensing_server_set_data_queueing(&data) )
    {
        return RBLE_BUSY;
    }

    return RBLE_OK;
}

RBLE_STATUS ENVIRONMENTAL_SENSING_Server_Set_Value(uint16_t char_hdl, uint8_t *char_val)
{
    uint16_t len = 0;
    SET_DATA_INFO data;

    if (ENVIRONMENTAL_SENSING_SERVER_STATE_CONNECTED != info.state) {
        return RBLE_STATUS_ERROR;
    }

    if( NULL == char_val )
    {
        return RBLE_PARAM_ERR;
    }

    switch( char_hdl )
    {
    case ENVIRONMENTAL_SENSING_HDL_ES_DESCRIPTOR_VALUE_CHANGED_CCCD:
        len = 2;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_DESCRIPTOR_VALUE_CHANGED_VAL:
		len = 1;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_APPARENT_WIND_DIRECTION_CCCD:
        len = 2;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_APPARENT_WIND_DIRECTION_VAL:
        len = 2;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_APPARENT_WIND_SPEED_CCCD:
        len = 2;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_APPARENT_WIND_SPEED_VAL:
        len = 2;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_DEW_POINT_CCCD:
        len = 2;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_DEW_POINT_VAL:
        len = 1;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_ELEVATION_CCCD:
        len = 2;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_ELEVATION_VAL:
        len = 3;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_GUST_FACTOR_CCCD:
        len = 2;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_GUST_FACTOR_VAL:
        len = 1;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_HEAT_INDEX_CCCD:
        len = 2;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_HEAT_INDEX_VAL:
        len = 1;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_HUMIDITY_CCCD:
        len = 2;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_HUMIDITY_VAL:
        len = 2;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_IRRADIANCE_CCCD:
        len = 2;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_IRRADIANCE_VAL:
        len = 2;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_POLLEN_CONCENTRATION_CCCD:
        len = 2;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_POLLEN_CONCENTRATION_VAL:
        len = 3;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_RAINFALL_CCCD:
        len = 2;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_RAINFALL_VAL:
        len = 2;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_PRESSURE_CCCD:
        len = 2;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_PRESSURE_VAL:
        len = 4;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_TEMPERATURE_CCCD:
        len = 2;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_TEMPERATURE_VAL:
        len = 2;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_TRUE_WIND_DIRECTION_CCCD:
        len = 2;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_TRUE_WIND_DIRECTION_VAL:
        len = 2;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_TRUE_WIND_SPEED_CCCD:
        len = 2;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_TRUE_WIND_SPEED_VAL:
        len = 2;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_UV_INDEX_CCCD:
        len = 2;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_UV_INDEX_VAL:
        len = 1;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_WIND_CHILL_CCCD:
        len = 2;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_WIND_CHILL_VAL:
        len = 1;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_BAROMETRIC_PRESSURE_TREND_CCCD:
        len = 2;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_BAROMETRIC_PRESSURE_TREND_VAL:
        len = 1;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_MAGNETIC_DECLINATION_CCCD:
        len = 2;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_MAGNETIC_DECLINATION_VAL:
        len = 2;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_MAGNETIC_FLUX_DENSITY___2D_CCCD:
        len = 2;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_MAGNETIC_FLUX_DENSITY___2D_VAL:
        len = 4;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_MAGNETIC_FLUX_DENSITY___3D_CCCD:
        len = 2;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_ES_MAGNETIC_FLUX_DENSITY___3D_VAL:
        len = 6;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_DI_MANUFACTURER_NAME_STRING_VAL:
        len = 7;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_DI_MODEL_NUMBER_STRING_VAL:
        len = 7;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_DI_SERIAL_NUMBER_STRING_VAL:
        len = 7;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_DI_HARDWARE_REVISION_STRING_VAL:
        len = 7;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_DI_FIRMWARE_REVISION_STRING_VAL:
        len = 7;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_DI_SOFTWARE_REVISION_STRING_VAL:
        len = 7;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_DI_SYSTEM_ID_VAL:
        len = 8;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_DI_IEEE_11073_20601_REGULATORY_CERTIFICATION_DATA_LIST_VAL:
        len = 6;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_DI_PNP_ID_VAL:
        len = 7;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_BS_BATTERY_LEVEL_CCCD:
        len = 2;
        break;
        
    case ENVIRONMENTAL_SENSING_HDL_BS_BATTERY_LEVEL_VAL:
        len = 1;
        break;
        
    default:
        return RBLE_PARAM_ERR;
    }

    data.hdl = char_hdl;
    data.len = len;
    memcpy(data.value, char_val, data.len);
    data.send_ntf_ind = ENVIRONMENTAL_SENSING_SERVER_DESC_ALL_DISABLE;
    data.write_cmd_ind = FALSE;
    if( FALSE == environmental_sensing_server_set_data_queueing(&data) )
    {
        return RBLE_BUSY;
    }

    return RBLE_OK;
}
